function testYangLedgerBasisSafety()
%TESTYANGLEDGERBASISSAFETY FI-8 physical-mole accounting guard.
%
% Tier: Unit. Final item: FI-8. Runtime class: < 10 s. Default smoke: no.
% Failure mode caught: native/nondimensional rows produce apparent H2
% metrics or balances on a false physical mole basis.

    componentNames = ["H2"; "CO2"];
    ledger = makeYangFourBedLedger(componentNames, ...
        'LedgerNote', "FI-8 basis safety");
    common = {'CycleIndex', 1, 'SlotIndex', 1, 'OperationGroupId', "basis-unsafe", ...
        'PairId', "none", 'StageLabel', "AD", 'DirectTransferFamily', "none", ...
        'Basis', "native_counter_tail_delta", 'Units', "native_integrated_units"};

    ledger = appendYangLedgerStreamRows(ledger, componentNames, [1.0; 0.2], common{:}, ...
        'RecordId', "A-01", 'YangLabel', "AD", 'GlobalBed', "A", ...
        'LocalIndex', 1, 'LocalRole', "adsorber", ...
        'StreamScope', "external_feed", 'StreamDirection', "in", ...
        'Endpoint', "feed_end");
    ledger = appendYangLedgerStreamRows(ledger, componentNames, [0.8; 0.01], common{:}, ...
        'RecordId', "A-01", 'YangLabel', "AD", 'GlobalBed', "A", ...
        'LocalIndex', 1, 'LocalRole', "adsorber", ...
        'StreamScope', "external_product", 'StreamDirection', "out", ...
        'Endpoint', "product_end");
    ledger = appendYangLedgerStreamRows(ledger, componentNames, [0.2; 0.19], common{:}, ...
        'RecordId', "A-01", 'YangLabel', "AD", 'GlobalBed', "A", ...
        'LocalIndex', 1, 'LocalRole', "adsorber", ...
        'StreamScope', "bed_inventory_delta", 'StreamDirection', "delta", ...
        'Endpoint', "not_applicable", 'AllowSignedMoles', true);

    metrics = computeYangPerformanceMetrics(ledger, 'TargetProductComponent', "H2");
    assert(all(~metrics.rows.pass));
    assert(all(isnan(metrics.rows.value)));
    assert(any(contains(metrics.rows.notes, "physical mol units") | ...
        contains(metrics.rows.notes, "incompatible basis token 'native'")));

    [balanceRows, summary] = computeYangLedgerBalances(ledger);
    assert(~summary.pass);
    assert(summary.nInvalidBasisRows > 0);
    assert(all(~balanceRows.pass));
    assert(any(contains(balanceRows.notes, "physical mol units") | ...
        contains(balanceRows.notes, "incompatible basis token 'native'")));

    converted = makeYangFourBedLedger(componentNames, ...
        'LedgerNote', "FI-8 converted native basis safety");
    convertedCommon = {'CycleIndex', 1, 'SlotIndex', 1, ...
        'OperationGroupId', "basis-converted", ...
        'PairId', "none", 'StageLabel', "AD", 'DirectTransferFamily', "none", ...
        'Basis', "physical_moles_from_native_counter_tail_delta_using_params.nScaleFac", ...
        'Units', "mol"};
    converted = appendYangLedgerStreamRows(converted, componentNames, [1.0; 0.2], convertedCommon{:}, ...
        'RecordId', "A-01", 'YangLabel', "AD", 'GlobalBed', "A", ...
        'LocalIndex', 1, 'LocalRole', "adsorber", ...
        'StreamScope', "external_feed", 'StreamDirection', "in", ...
        'Endpoint', "feed_end");
    converted = appendYangLedgerStreamRows(converted, componentNames, [0.8; 0.01], convertedCommon{:}, ...
        'RecordId', "A-01", 'YangLabel', "AD", 'GlobalBed', "A", ...
        'LocalIndex', 1, 'LocalRole', "adsorber", ...
        'StreamScope', "external_product", 'StreamDirection', "out", ...
        'Endpoint', "product_end");
    converted = appendYangLedgerStreamRows(converted, componentNames, [0.2; 0.19], ...
        'CycleIndex', 1, 'SlotIndex', 1, ...
        'OperationGroupId', "basis-converted", ...
        'PairId', "none", 'StageLabel', "AD", 'DirectTransferFamily', "none", ...
        'Basis', "physical_moles_from_available_scale_factors", ...
        'Units', "mol", ...
        'RecordId', "A-01", 'YangLabel', "AD", 'GlobalBed', "A", ...
        'LocalIndex', 1, 'LocalRole', "adsorber", ...
        'StreamScope', "bed_inventory_delta", 'StreamDirection', "delta", ...
        'Endpoint', "not_applicable", 'AllowSignedMoles', true);

    compat = checkYangLedgerPhysicalMoleCompatibility(converted.streamRows, ...
        ["external_feed"; "external_product"; "bed_inventory_delta"]);
    assert(compat.pass);
    convertedMetrics = computeYangPerformanceMetrics(converted, ...
        'TargetProductComponent', "H2");
    assert(all(convertedMetrics.rows.pass));
    [~, convertedSummary] = computeYangLedgerBalances(converted);
    assert(convertedSummary.pass);
    assert(convertedSummary.nInvalidBasisRows == 0);

    fprintf('FI-8 ledger basis safety passed: native-unit rows do not yield physical metrics/balances.\n');
end
