function testYangPairLocalConservation()
%TESTYANGPAIRLOCALCONSERVATION T-CONS-01 pair-local conservation.
%
% Tier: Unit. Runtime class: < 10 s. Default smoke: yes.
% Failure modes caught: LEDGER-03 component balance drift and PAIR-02
% direct-transfer cancellation/sign confusion.

    [manifest, pairMap] = buildWp5ManifestContext();
    componentNames = ["H2"; "CO2"];
    ledger = makeYangFourBedLedger(componentNames, ...
        'Manifest', manifest, 'PairMap', pairMap, ...
        'LedgerNote', "T-CONS-01 pair-local conservation");

    ledger = appendYangLedgerStreamRows(ledger, componentNames, [1.0; 0.1], ...
        'CycleIndex', 1, 'SlotIndex', 3, 'OperationGroupId', "EQI-A-to-C", ...
        'RecordId', "A-03", 'PairId', "EQI-A-to-C", ...
        'StageLabel', "EQI", 'DirectTransferFamily', "EQI", ...
        'YangLabel', "EQI-BD", 'GlobalBed', "A", 'LocalIndex', 1, ...
        'LocalRole', "donor", 'StreamScope', "internal_transfer", ...
        'StreamDirection', "out_of_donor", 'Endpoint', "product_end", ...
        'Basis', "synthetic");
    ledger = appendYangLedgerStreamRows(ledger, componentNames, [1.0; 0.1], ...
        'CycleIndex', 1, 'SlotIndex', 3, 'OperationGroupId', "EQI-A-to-C", ...
        'RecordId', "C-09", 'PairId', "EQI-A-to-C", ...
        'StageLabel', "EQI", 'DirectTransferFamily', "EQI", ...
        'YangLabel', "EQI-PR", 'GlobalBed', "C", 'LocalIndex', 2, ...
        'LocalRole', "receiver", 'StreamScope', "internal_transfer", ...
        'StreamDirection', "into_receiver", 'Endpoint', "product_end", ...
        'Basis', "synthetic");
    ledger = appendYangLedgerStreamRows(ledger, componentNames, [-1.0; -0.1], ...
        'CycleIndex', 1, 'SlotIndex', 3, 'OperationGroupId', "EQI-A-to-C", ...
        'RecordId', "A-03", 'PairId', "EQI-A-to-C", ...
        'StageLabel', "EQI", 'DirectTransferFamily', "EQI", ...
        'YangLabel', "EQI-BD", 'GlobalBed', "A", 'LocalIndex', 1, ...
        'LocalRole', "donor", 'StreamScope', "bed_inventory_delta", ...
        'StreamDirection', "delta", 'Endpoint', "not_applicable", ...
        'Basis', "computed_inventory");
    ledger = appendYangLedgerStreamRows(ledger, componentNames, [1.0; 0.1], ...
        'CycleIndex', 1, 'SlotIndex', 3, 'OperationGroupId', "EQI-A-to-C", ...
        'RecordId', "C-09", 'PairId', "EQI-A-to-C", ...
        'StageLabel', "EQI", 'DirectTransferFamily', "EQI", ...
        'YangLabel', "EQI-PR", 'GlobalBed', "C", 'LocalIndex', 2, ...
        'LocalRole', "receiver", 'StreamScope', "bed_inventory_delta", ...
        'StreamDirection', "delta", 'Endpoint', "not_applicable", ...
        'Basis', "computed_inventory");

    [balanceRows, summary] = computeYangLedgerBalances(ledger, ...
        'AbsTol', 1e-12, 'RelTol', 1e-12);
    assert(summary.pass);
    assert(all(abs(balanceRows.residual_moles) <= balanceRows.tolerance_moles));
    assert(any(balanceRows.balance_scope == "slot_internal_transfer"));
    assert(any(ledger.streamRows.stage_label == "EQI"));

    fprintf('T-CONS-01 passed: pair-local internal transfer and inventory balance close.\n');
end

function [manifest, pairMap] = buildWp5ManifestContext()
    manifest = getYangFourBedScheduleManifest();
    pairMap = getYangDirectTransferPairMap(manifest);
end
