function testYangLedgerArtifactsWrite()
%TESTYANGLEDGERARTIFACTSWRITE FI-8 compact ledger artifact writer.
%
% Tier: Unit. Final item: FI-8. Runtime class: < 10 s. Default smoke: no.
% Failure mode caught: commissioning handoff cannot persist stream,
% balance, metric, and summary ledger artifacts.

    componentNames = ["H2"; "CO2"];
    ledger = makeYangFourBedLedger(componentNames, ...
        'LedgerNote', "FI-8 ledger artifact test");
    common = {'CycleIndex', 1, 'SlotIndex', 1, 'OperationGroupId', "artifact", ...
        'PairId', "none", 'StageLabel', "AD", 'DirectTransferFamily', "none", ...
        'Basis', "synthetic_physical_moles", 'Units', "mol"};
    ledger = appendYangLedgerStreamRows(ledger, componentNames, [1.0; 0.2], common{:}, ...
        'RecordId', "A-01", 'YangLabel', "AD", 'GlobalBed', "A", ...
        'LocalIndex', 1, 'LocalRole', "adsorber", ...
        'StreamScope', "external_feed", 'StreamDirection', "in", ...
        'Endpoint', "feed_end");
    ledger = appendYangLedgerStreamRows(ledger, componentNames, [0.8; 0.01], common{:}, ...
        'RecordId', "A-01", 'YangLabel', "AD", 'GlobalBed', "A", ...
        'LocalIndex', 1, 'LocalRole', "adsorber", ...
        'StreamScope', "external_product", 'StreamDirection', "out", ...
        'Endpoint', "product_end");
    ledger = appendYangLedgerStreamRows(ledger, componentNames, [0.2; 0.19], common{:}, ...
        'RecordId', "A-01", 'YangLabel', "AD", 'GlobalBed', "A", ...
        'LocalIndex', 1, 'LocalRole', "adsorber", ...
        'StreamScope', "bed_inventory_delta", 'StreamDirection', "delta", ...
        'Endpoint', "not_applicable", 'AllowSignedMoles', true);

    [balanceRows, ~] = computeYangLedgerBalances(ledger);
    metrics = computeYangPerformanceMetrics(ledger);
    ledger.balanceRows = balanceRows;
    ledger.metricRows = metrics.rows;

    outDir = fullfile(tempdir, "yang_ledger_artifact_test_" + string(java.util.UUID.randomUUID));
    status = writeYangFourBedLedgerArtifacts(ledger, outDir, 'FileStem', "commissioning");

    assert(status.pass);
    assert(numel(status.paths) == 4);
    assert(all(isfile(status.paths)));
    assert(all(status.bytes > 0));
    txt = fileread(fullfile(outDir, "commissioning_summary.json"));
    assert(contains(txt, "internalTransfersExcludedFromProduct"));

    fprintf('FI-8 ledger artifact writer passed: compact CSV/JSON handoff files written.\n');
end
