function testYangFullSlotLedgerBalance()
%TESTYANGFULLSLOTLEDGERBALANCE T-CONS-02 full-slot balance.
%
% Tier: Integration/sanity. Runtime class: < 10 s. Default smoke: yes.
% Failure modes caught: LEDGER-01 product overcount, LEDGER-02 split drift,
% and LEDGER-03 slot-level component imbalance.

    [manifest, pairMap] = buildWp5ManifestContext();
    componentNames = ["H2"; "CO2"];
    ledger = makeYangFourBedLedger(componentNames, ...
        'Manifest', manifest, 'PairMap', pairMap, ...
        'LedgerNote', "T-CONS-02 PP_PU full-slot balance");

    common = {'CycleIndex', 1, 'SlotIndex', 4, 'OperationGroupId', "PP-B-to-A", ...
        'PairId', "PP_PU-B-to-A", 'StageLabel', "PP_PU", ...
        'DirectTransferFamily', "PP_PU", 'Basis', "synthetic"};
    ledger = appendYangLedgerStreamRows(ledger, componentNames, [1.0; 0.10], common{:}, ...
        'RecordId', "B-06", 'YangLabel', "PP", 'GlobalBed', "B", ...
        'LocalIndex', 1, 'LocalRole', "donor", ...
        'StreamScope', "internal_transfer", 'StreamDirection', "out_of_donor", ...
        'Endpoint', "product_end");
    ledger = appendYangLedgerStreamRows(ledger, componentNames, [1.0; 0.10], common{:}, ...
        'RecordId', "A-07", 'YangLabel', "PU", 'GlobalBed', "A", ...
        'LocalIndex', 2, 'LocalRole', "receiver", ...
        'StreamScope', "internal_transfer", 'StreamDirection', "into_receiver", ...
        'Endpoint', "product_end");
    ledger = appendYangLedgerStreamRows(ledger, componentNames, [0.2; 0.05], common{:}, ...
        'RecordId', "A-07", 'YangLabel', "PU", 'GlobalBed', "A", ...
        'LocalIndex', 2, 'LocalRole', "receiver", ...
        'StreamScope', "external_waste", 'StreamDirection', "out", ...
        'Endpoint', "feed_end");
    ledger = appendYangLedgerStreamRows(ledger, componentNames, [-0.2; -0.05], common{:}, ...
        'RecordId', "PP-PU-total", 'YangLabel', "PP/PU", 'GlobalBed', "all_participating", ...
        'LocalIndex', NaN, 'LocalRole', "all_participating", ...
        'StreamScope', "bed_inventory_delta", 'StreamDirection', "delta", ...
        'Endpoint', "not_applicable", 'Basis', "computed_inventory");

    [balanceRows, summary] = computeYangLedgerBalances(ledger, ...
        'AbsTol', 1e-12, 'RelTol', 1e-12);
    assert(summary.pass);
    assert(all(abs(balanceRows.residual_moles) <= balanceRows.tolerance_moles));
    assert(sum(ledger.streamRows.moles(ledger.streamRows.stream_scope == "external_product")) == 0);
    assert(sum(ledger.streamRows.moles(ledger.streamRows.stream_scope == "internal_transfer")) > 0);

    fprintf('T-CONS-02 passed: full-slot external balance closes and internal transfers cancel.\n');
end

function [manifest, pairMap] = buildWp5ManifestContext()
    manifest = getYangFourBedScheduleManifest();
    pairMap = getYangDirectTransferPairMap(manifest);
end
