function testYangAdppBfLedgerSplit()
%TESTYANGADPPBFLEDGERSPLIT T-PAIR-04 AD&PP/BF split audit.
%
% Tier: Unit. Runtime class: < 10 s. Default smoke: yes.
% Failure modes caught: SCHED-03 compound AD&PP collapse, LEDGER-02 BF
% internal gas counted as external product.

    [manifest, pairMap] = buildWp5ManifestContext();
    componentNames = ["H2"; "CO2"];
    ledger = buildAdppBfLedger(componentNames, manifest, pairMap, [1.0; 0.0]);

    [balanceRows, balanceSummary] = computeYangLedgerBalances(ledger, ...
        'AbsTol', 1e-12, 'RelTol', 1e-12);
    assert(balanceSummary.pass);
    assert(all(abs(balanceRows.residual_moles) <= balanceRows.tolerance_moles));

    metrics = computeYangPerformanceMetrics(ledger, 'TargetProductComponent', "H2");
    purity = getMetric(metrics, "product_purity");
    recovery = getMetric(metrics, "product_recovery");
    assertClose(purity, 7.0 / 7.01, 1e-12);
    assertClose(recovery, 7.0 / 10.0, 1e-12);

    ledgerWithLargeInternal = buildAdppBfLedger(componentNames, manifest, pairMap, [500.0; 30.0]);
    metricsWithLargeInternal = computeYangPerformanceMetrics(ledgerWithLargeInternal, ...
        'TargetProductComponent', "H2");
    assertClose(getMetric(metricsWithLargeInternal, "product_purity"), purity, 1e-12);
    assertClose(getMetric(metricsWithLargeInternal, "product_recovery"), recovery, 1e-12);

    fprintf('T-PAIR-04 passed: AD&PP external product is separated from BF internal transfer.\n');
end

function ledger = buildAdppBfLedger(componentNames, manifest, pairMap, internalMoles)
    ledger = makeYangFourBedLedger(componentNames, ...
        'Manifest', manifest, 'PairMap', pairMap, ...
        'LedgerNote', "T-PAIR-04 ADPP_BF split");
    common = {'CycleIndex', 1, 'SlotIndex', 2, 'OperationGroupId', "ADPP-A-to-B", ...
        'PairId', "ADPP_BF-A-to-B", 'StageLabel', "ADPP_BF", ...
        'DirectTransferFamily', "ADPP_BF", 'Basis', "synthetic"};

    ledger = appendYangLedgerStreamRows(ledger, componentNames, [10.0; 2.0], common{:}, ...
        'RecordId', "A-02", 'YangLabel', "AD&PP", 'GlobalBed', "A", ...
        'LocalIndex', 1, 'LocalRole', "donor", ...
        'StreamScope', "external_feed", 'StreamDirection', "in", ...
        'Endpoint', "feed_end");
    ledger = appendYangLedgerStreamRows(ledger, componentNames, [7.0; 0.01], common{:}, ...
        'RecordId', "A-02", 'YangLabel', "AD&PP", 'GlobalBed', "A", ...
        'LocalIndex', 1, 'LocalRole', "donor", ...
        'StreamScope', "external_product", 'StreamDirection', "out", ...
        'Endpoint', "product_end");
    ledger = appendYangLedgerStreamRows(ledger, componentNames, internalMoles, common{:}, ...
        'RecordId', "A-02", 'YangLabel', "AD&PP", 'GlobalBed', "A", ...
        'LocalIndex', 1, 'LocalRole', "donor", ...
        'StreamScope', "internal_transfer", 'StreamDirection', "out_of_donor", ...
        'Endpoint', "product_end");
    ledger = appendYangLedgerStreamRows(ledger, componentNames, internalMoles, common{:}, ...
        'RecordId', "B-02", 'YangLabel', "BF", 'GlobalBed', "B", ...
        'LocalIndex', 2, 'LocalRole', "receiver", ...
        'StreamScope', "internal_transfer", 'StreamDirection', "into_receiver", ...
        'Endpoint', "product_end");
    ledger = appendYangLedgerStreamRows(ledger, componentNames, [3.0; 1.99], common{:}, ...
        'RecordId', "ADPP-BF-total", 'YangLabel', "AD&PP/BF", 'GlobalBed', "all_participating", ...
        'LocalIndex', NaN, 'LocalRole', "all_participating", ...
        'StreamScope', "bed_inventory_delta", 'StreamDirection', "delta", ...
        'Endpoint', "not_applicable", 'Basis', "computed_inventory");
end

function value = getMetric(metrics, metricName)
    row = metrics.rows(metrics.rows.metric_name == string(metricName), :);
    assert(height(row) == 1);
    value = row.value(1);
end

function assertClose(actual, expected, tol)
    assert(abs(actual - expected) <= tol);
end

function [manifest, pairMap] = buildWp5ManifestContext()
    manifest = getYangFourBedScheduleManifest();
    pairMap = getYangDirectTransferPairMap(manifest);
end
