function testYangNativeAdFeedClosureCycleBalance()
%TESTYANGNATIVEADFEEDCLOSURECYCLEBALANCE FI-7 native AD feed closure.
%
% Tier: Sanity/integration. Final items: FI-6/FI-7/FI-8. Runtime class:
% < 60 s. Default smoke: no. Failure mode caught: native HP-FEE-RAF AD
% column counters omit feed-side external input, leaving H2 slot and cycle
% ledger balances open even when rows are in physical moles.

    params = buildYangH2Co2AcTemplateParams('NVols', 2, 'NCols', 2, ...
        'NSteps', 1, 'FinalizeForRuntime', true);
    manifest = getYangFourBedScheduleManifest();
    pairMap = getYangDirectTransferPairMap(manifest);
    container = makeCommissioningContainer(params, manifest, pairMap);
    controls = struct( ...
        'cycleTimeSec', 2.4, ...
        'adapterValidationOnly', false, ...
        'Cv_PP_PU_internal', 1e-6, ...
        'Cv_PU_waste', 1e-6, ...
        'Cv_ADPP_feed', 1e-6, ...
        'Cv_ADPP_product', 1e-6, ...
        'Cv_ADPP_BF_internal', 1e-6);

    [~, ~, report] = evalc('runYangFourBedCycle(container, params, controls)');
    balanceRows = report.ledger.balanceRows;
    adH2 = balanceRows(balanceRows.balance_scope == "slot_external" & ...
        balanceRows.stage_label == "AD" & balanceRows.component == "H2", :);
    assert(height(adH2) == 4);
    assert(all(adH2.pass));

    cycleH2 = balanceRows(balanceRows.balance_scope == "cycle_external" & ...
        balanceRows.component == "H2", :);
    assert(height(cycleH2) == 1);
    assert(cycleH2.pass);
    assert(report.balanceSummary.nInvalidBasisRows == 0);
    assert(numel(report.operationReports) == 24);

    closureRows = report.ledger.streamRows( ...
        report.ledger.streamRows.stream_scope == "external_feed" & ...
        report.ledger.streamRows.stage_label == "AD" & ...
        report.ledger.streamRows.basis == ...
            "physical_moles_reconstructed_from_ad_slot_balance", :);
    assert(height(closureRows) > 0);

    fprintf('FI-7 native AD feed closure passed: one real cycle closes AD H2 slot and cycle balances.\n');
end

function container = makeCommissioningContainer(params, manifest, pairMap)
    states = struct();
    beds = ["A", "B", "C", "D"];
    for i = 1:numel(beds)
        one = [0.76 - 0.01 * i; 0.24 + 0.01 * i; 0.01; 0.02; 1.0; 1.0];
        states.("state_" + beds(i)) = extractYangPhysicalBedState(params, ...
            repmat(one, params.nVols, 1));
    end
    container = makeYangFourBedStateContainer(states, ...
        'Manifest', manifest, ...
        'PairMap', pairMap, ...
        'InitializationPolicy', "FI-7 native AD feed closure regression", ...
        'SourceNote', "synthetic physical states");
end
