function testYangFourBedLedgerSchema()
%TESTYANGFOURBEDLEDGERSCHEMA WP5 ledger schema and assumptions.
%
% Tier: Static/source. Runtime class: < 10 s. Default smoke: yes.
% Failure modes caught: LEDGER-01 internal-transfer/product confusion and
% DOC-01 missing output assumptions.

    [manifest, pairMap] = buildWp5ManifestContext();
    componentNames = ["H2"; "CO2"; "CO"; "CH4"];
    ledger = makeYangFourBedLedger(componentNames, ...
        'Manifest', manifest, ...
        'PairMap', pairMap, ...
        'LedgerNote', "T-DOC-01 schema test");

    result = validateYangFourBedLedger(ledger);
    assert(result.pass);
    assert(ledger.architecture.noDynamicInternalTanks);
    assert(~ledger.architecture.internalTransfersCountAsExternalProduct);
    assert(isequal(string(ledger.componentNames), componentNames));

    ledger = appendYangLedgerStreamRows(ledger, componentNames, [1.0; 0.1; 0.0; 0.0], ...
        'CycleIndex', 1, ...
        'SlotIndex', 1, ...
        'OperationGroupId', "EQI-B-to-D", ...
        'RecordId', "B-05", ...
        'PairId', "EQI-B-to-D", ...
        'StageLabel', "EQI", ...
        'DirectTransferFamily', "EQI", ...
        'YangLabel', "EQI-BD", ...
        'GlobalBed', "B", ...
        'LocalIndex', 1, ...
        'LocalRole', "donor", ...
        'StreamScope', "internal_transfer", ...
        'StreamDirection', "out_of_donor", ...
        'Endpoint', "product_end", ...
        'Basis', "synthetic", ...
        'Notes', "T-DOC-01 synthetic internal transfer");
    result = validateYangFourBedLedger(ledger);
    assert(result.pass);
    assert(all(ledger.streamRows.stream_scope == "internal_transfer"));
    assert(~any(ledger.streamRows.stream_scope == "external_product"));

    badMetadata = ledger.metadata;
    badMetadata = rmfield(badMetadata, 'eventPolicy');
    badResult = validateYangFourBedRunMetadata(badMetadata);
    assert(~badResult.pass);

    fprintf('T-DOC-01 ledger schema passed: WP5 ledger assumptions are explicit.\n');
end

function [manifest, pairMap] = buildWp5ManifestContext()
    manifest = getYangFourBedScheduleManifest();
    pairMap = getYangDirectTransferPairMap(manifest);
end
