function testYangEqStageLedgerSeparation()
%TESTYANGEQSTAGELEDGERSEPARATION T-PAIR-02 EQ stage ledger split.
%
% Tier: Unit. Runtime class: < 10 s. Default smoke: yes.
% Failure mode caught: PAIR-03 EQI and EQII collapsed into generic EQ.

    [manifest, pairMap, container] = buildWp5SentinelContext();
    componentNames = ["H2"; "CO2"];
    ledger = makeYangFourBedLedger(componentNames, ...
        'Manifest', manifest, 'PairMap', pairMap, ...
        'LedgerNote', "T-PAIR-02 EQ stage separation");

    eqiCase = makeYangTemporaryPairedCase(selectPair(container, pairMap, "EQI", "B", "D"), ...
        'DurationSeconds', 1);
    eqiiCase = makeYangTemporaryPairedCase(selectPair(container, pairMap, "EQII", "A", "D"), ...
        'DurationSeconds', 1);
    eqiSpec = classifyYangLedgerOperation(eqiCase);
    eqiiSpec = classifyYangLedgerOperation(eqiiCase);
    assert(eqiSpec.stage_label == "EQI");
    assert(eqiiSpec.stage_label == "EQII");
    assert(eqiSpec.stage_label ~= eqiiSpec.stage_label);

    ledger = appendEqPair(ledger, componentNames, "EQI", "EQI-B-to-D", [1.0; 0.10]);
    ledger = appendEqPair(ledger, componentNames, "EQII", "EQII-A-to-D", [0.5; 0.05]);
    summary = summarizeYangFourBedLedger(ledger);
    stages = unique(summary.streamTotals.stage_label);
    assert(ismember("EQI", stages));
    assert(ismember("EQII", stages));
    assert(~ismember("EQ", stages));

    fprintf('T-PAIR-02 passed: EQI and EQII remain distinct in ledger metadata.\n');
end

function ledger = appendEqPair(ledger, componentNames, stageLabel, operationGroupId, moles)
    ledger = appendYangLedgerStreamRows(ledger, componentNames, moles, ...
        'CycleIndex', 1, 'SlotIndex', 1, 'OperationGroupId', operationGroupId, ...
        'RecordId', stageLabel + "-donor", 'PairId', operationGroupId, ...
        'StageLabel', stageLabel, 'DirectTransferFamily', stageLabel, ...
        'YangLabel', stageLabel + "-BD", 'GlobalBed', "A", 'LocalIndex', 1, ...
        'LocalRole', "donor", 'StreamScope', "internal_transfer", ...
        'StreamDirection', "out_of_donor", 'Endpoint', "product_end", ...
        'Basis', "synthetic");
    ledger = appendYangLedgerStreamRows(ledger, componentNames, moles, ...
        'CycleIndex', 1, 'SlotIndex', 1, 'OperationGroupId', operationGroupId, ...
        'RecordId', stageLabel + "-receiver", 'PairId', operationGroupId, ...
        'StageLabel', stageLabel, 'DirectTransferFamily', stageLabel, ...
        'YangLabel', stageLabel + "-PR", 'GlobalBed', "B", 'LocalIndex', 2, ...
        'LocalRole', "receiver", 'StreamScope', "internal_transfer", ...
        'StreamDirection', "into_receiver", 'Endpoint', "product_end", ...
        'Basis', "synthetic");
end

function selection = selectPair(container, pairMap, family, donor, receiver)
    pair = pairMap.transferPairs( ...
        pairMap.transferPairs.direct_transfer_family == string(family) & ...
        pairMap.transferPairs.donor_bed == string(donor) & ...
        pairMap.transferPairs.receiver_bed == string(receiver), :);
    assert(height(pair) == 1);
    selection = selectYangFourBedPairStates(container, pair);
end

function [manifest, pairMap, container] = buildWp5SentinelContext()
    manifest = getYangFourBedScheduleManifest();
    pairMap = getYangDirectTransferPairMap(manifest);
    states = struct();
    states.state_A = struct("bed", "A", "payload", 101);
    states.state_B = struct("bed", "B", "payload", 202);
    states.state_C = struct("bed", "C", "payload", 303);
    states.state_D = struct("bed", "D", "payload", 404);
    container = makeYangFourBedStateContainer(states, ...
        'Manifest', manifest, 'PairMap', pairMap, ...
        'InitializationPolicy', "unit_test_distinguishable_sentinel_states", ...
        'SourceNote', "T-PAIR-02 synthetic sentinel states");
end
