% Tier 3 pressure-program sanity test for the Schell native adapter.
%
% Failure mode caught: RP-FEE-XXX repressurises to the artificial feed-tank
% pressure, starving the intended HP-FEE-RAF H2 product step.
%
% Runtime class: about one minute on local MATLAB R2026a.
% Not included in default smoke/sanity runners.

repoRoot = fileparts(fileparts(mfilename("fullpath")));
addpath(genpath(repoRoot));

fprintf("Tier 3 sanity: checking Schell pressure programme and HP flow.\n");

caseId = "schell_20bar_tads40_performance_central";
options.thermal_mode = "isothermal_pressure_program_test";
options.time_points_per_step = 6;

[params, fullParams, runConfig] = build_schell_runnable_params( ...
    caseId, 1, options);

assert(fullParams.presFeTa > fullParams.presColHigh, ...
    "test_schell_pressure_program:missingFeedHeadroom", ...
    "Feed tank pressure must remain above the source high-pressure setpoint.");
expectedPressValveRelative = ...
    runConfig.pressurization_valve_reference_relative_before_flow_basis_conversion ...
    * runConfig.flow_basis_old_to_converted_factor;
assertClose(runConfig.pressurization_valve_relative_to_adsorption, ...
    expectedPressValveRelative, 1e-12, ...
    "flow-basis-rescaled RP-FEE-XXX valve ratio");
assert(runConfig.pressurization_valve_relative_to_adsorption < 1.0, ...
    "test_schell_pressure_program:pressValveNotSeparated", ...
    "RP-FEE-XXX must use a separate, smaller valve than HP-FEE-RAF.");

rpMask = strcmp(fullParams.sStepCol, "RP-FEE-XXX");
hpMask = strcmp(fullParams.sStepCol, "HP-FEE-RAF");
assert(all(fullParams.valFeedCol(rpMask) < min(fullParams.valFeedCol(hpMask))), ...
    "test_schell_pressure_program:rpReusesAdsValve", ...
    "RP-FEE-XXX must not reuse the adsorption feed valve coefficient.");

sol = runPsaCycle(params);
[~, ledgerTable] = extract_schell_step_ledger(fullParams, sol, runConfig);

rpRows = ledgerTable(ledgerTable.step_name == "RP-FEE-XXX", :);
hpRows = ledgerTable(ledgerTable.step_name == "HP-FEE-RAF", :);

assert(~isempty(rpRows), ...
    "test_schell_pressure_program:missingRepressurizationRows", ...
    "Ledger must include RP-FEE-XXX rows.");
assert(~isempty(hpRows), ...
    "test_schell_pressure_program:missingHighPressureFeedRows", ...
    "Ledger must include HP-FEE-RAF rows.");

rpEnd = rpRows.pressure_end_bar;
assert(max(rpEnd) <= fullParams.presColHigh + 0.5, ...
    "test_schell_pressure_program:repressurizationOvershoots", ...
    "RP-FEE-XXX must not repressurise to the feed-tank pressure.");
assert(min(rpEnd) >= fullParams.presColHigh - 1.0, ...
    "test_schell_pressure_program:repressurizationUnderTarget", ...
    "RP-FEE-XXX should end near the source high-pressure setpoint.");

hpStart = hpRows.pressure_start_bar;
assert(max(hpStart) <= fullParams.presColHigh + 0.5, ...
    "test_schell_pressure_program:hpStartsOverpressure", ...
    "HP-FEE-RAF must not start at the artificial feed-tank pressure.");

raffH2 = sum(hpRows.raffinate_external_product_moles_H2);
raffTotal = sum(hpRows.raffinate_external_product_moles_H2 ...
    + hpRows.raffinate_external_product_moles_CO2);
assert(raffH2 > 1e-3 && raffTotal > 1e-3, ...
    "test_schell_pressure_program:traceHpRaffinate", ...
    "HP-FEE-RAF must produce non-trace raffinate product flow.");

fprintf("Tier 3 sanity passed: Schell pressure programme keeps HP steps near %.1f bar and HP raffinate flow is non-trace.\n", ...
    fullParams.presColHigh);

function assertClose(actual, expected, tolerance, context)
    assert(isnumeric(actual), ...
        "test_schell_pressure_program:expectedNumeric", ...
        "Expected numeric value at %s.", context);
    actual = double(actual);
    expected = double(expected);
    assert(isequal(size(actual), size(expected)), ...
        "test_schell_pressure_program:sizeMismatch", ...
        "%s expected size %s, got %s.", context, ...
        mat2str(size(expected)), mat2str(size(actual)));
    if any(abs(actual - expected) > tolerance, "all")
        error("test_schell_pressure_program:numericMismatch", ...
            "%s expected %s, got %s.", context, ...
            mat2str(expected, 16), mat2str(actual, 16));
    end
end
