% Tier 3 stream-accounting sanity test for Schell SI subtraction reporting.
%
% Failure modes caught: comparing native external tank metrics to Schell
% Table 2 without reconstructing the SI subtraction accounting basis; and
% regressing Schell purge back to dynamic raffinate-tank material instead of
% equimolar feed-tank inventory.
%
% Source/policy basis: docs/source_reference/02_schell_2013_two_bed_psa_validation.md
% and docs/source_reference/topsail source guide/05_metrics_accounting_ledgers.md.
%
% Runtime class: about one minute on local MATLAB R2026a.
% Not included in default smoke/sanity runners.

repoRoot = fileparts(fileparts(mfilename("fullpath")));
addpath(genpath(repoRoot));

fprintf("Tier 3 sanity: checking Schell SI subtraction accounting labels.\n");

caseId = "schell_20bar_tads40_performance_central";
options.thermal_mode = "isothermal_si_accounting_test";
options.time_points_per_step = 6;

[params, fullParams, runConfig, scaffold, sourcePack] = ...
    build_schell_runnable_params(caseId, 1, options);

sol = runPsaCycle(params);
si = extract_schell_si_performance(fullParams, sol, 1);

expectedAdsorption = ...
    runConfig.expected_source_adsorption_moles_per_component_two_beds;
assertClose(expectedAdsorption, ...
    [0.6454327287216559, 0.6454327287216559], 1e-12, ...
    "central expected Schell source adsorption inventory");
assertClose(si.adsorption_feed_input_moles_by_component, ...
    expectedAdsorption, 8e-2, ...
    "last-cycle Schell SI adsorption inventory");
oldUnconvertedAdsorption = expectedAdsorption ...
    .* runConfig.flow_basis_old_to_converted_factor;
assert(all(si.adsorption_feed_input_moles_by_component ...
        < 0.10 .* oldUnconvertedAdsorption), ...
    "test_schell_si_accounting:oldFlowBasisNotRejected", ...
    "The old direct-20 native volFlowFeed interpretation must overpredict adsorption inventory decisively.");

assert(si.metrics_role == "validation_basis_candidate_schell_si", ...
    "test_schell_si_accounting:wrongSiRole", ...
    "Schell SI accounting must be labelled as a validation-basis candidate.");
assert(si.classification == "not_final_validation", ...
    "test_schell_si_accounting:prematureValidation", ...
    "Schell SI accounting must not be classified as final validation.");
assert(contains(si.validation_limitation, "HP-ATM-FEE"), ...
    "test_schell_si_accounting:missingPurgeRouteNote", ...
    "Schell SI accounting must identify the native feed-tank purge route.");

assert(~any(strcmp(fullParams.sStepCol, "LP-EXT-RAF"), "all"), ...
    "test_schell_si_accounting:dynamicRaffinatePurgeStillScheduled", ...
    "Schell purge must not schedule native LP-EXT-RAF dynamic raffinate-tank purge.");
assert(any(strcmp(fullParams.sStepCol, "HP-ATM-FEE"), "all"), ...
    "test_schell_si_accounting:feedTankPurgeMissing", ...
    "Schell purge must schedule native HP-ATM-FEE feed-tank product-end purge.");
assert(runConfig.purge_native_step == "HP-ATM-FEE", ...
    "test_schell_si_accounting:wrongPurgeRouteLabel", ...
    "Run config must label the native feed-tank purge route.");
assert(runConfig.purge_valve_relative_to_adsorption < 0.05, ...
    "test_schell_si_accounting:purgeValveNotPressureNormalized", ...
    "HP-ATM-FEE purge valve must be pressure-normalized for feed-tank headroom.");

assertPurgeUsesEquimolarFeedTank(si);

assertClose(si.feed_input_moles_by_component, ...
    si.H2_rich_adsorption_product_moles_by_component ...
    + si.Schell_basis_CO2_product_by_subtraction, ...
    1e-8, "Schell feed = H2-rich product + subtraction product");
assertClose(si.mass_balance_residual_by_component, ...
    zeros(size(si.mass_balance_residual_by_component)), ...
    1e-8, "Schell subtraction residual");

metricValues = [
    si.aggregate.h2_purity_fraction
    si.aggregate.h2_recovery_fraction
    si.aggregate.co2_purity_fraction
    si.aggregate.co2_recovery_fraction
];
assert(all(isfinite(metricValues)), ...
    "test_schell_si_accounting:nonfiniteSchellMetric", ...
    "Schell-basis purity/recovery fractions must be finite.");
assert(all(metricValues >= 0 & metricValues <= 1), ...
    "test_schell_si_accounting:unboundedSchellMetric", ...
    "Schell-basis purity/recovery fractions must be bounded by [0, 1].");

summary = extract_schell_summary(scaffold, fullParams, sol, runConfig, 0, ...
    fullfile(repoRoot, "validation", "reports", "schell_2013", ...
    "central", "summary.json"), ...
    fullfile(repoRoot, "validation", "reports", "schell_2013", ...
    "central", "raw.mat"), ...
    "central_css");

assert(isfield(summary.performance, "native_direct"), ...
    "test_schell_si_accounting:missingNativeMetrics", ...
    "Summary must include native direct diagnostic metrics.");
assert(isfield(summary.performance, "schell_si"), ...
    "test_schell_si_accounting:missingSchellMetrics", ...
    "Summary must include Schell SI subtraction-basis metrics.");
assert(summary.performance.native_direct.metrics_role ...
        == "diagnostic_native_direct", ...
    "test_schell_si_accounting:wrongNativeRole", ...
    "Native metrics must be distinctly labelled as diagnostics.");
assert(summary.performance.schell_si.metrics_role ...
        == "validation_basis_candidate_schell_si", ...
    "test_schell_si_accounting:wrongSummarySiRole", ...
    "Schell metrics must be distinctly labelled as validation-basis candidate.");
assert(summary.performance.native_direct.metrics_basis ...
        ~= summary.performance.schell_si.metrics_basis, ...
    "test_schell_si_accounting:undistinguishedMetricBasis", ...
    "Native and Schell-basis metric labels must be distinct.");
assert(contains(summary.performance.schell_si.metrics_basis, ...
        "subtraction"), ...
    "test_schell_si_accounting:missingSubtractionLabel", ...
    "Schell-basis metrics must explicitly identify subtraction accounting.");
assert(isfield(summary, "flow_basis_diagnostics"), ...
    "test_schell_si_accounting:missingFlowBasisDiagnostics", ...
    "Summary must include source expected versus observed flow-basis diagnostics.");
flowBasisDiagnostics = summary.flow_basis_diagnostics;
summaryExpectedAdsorption = flowBasisDiagnostics.expected_source_adsorption_moles_per_component_two_beds;
summaryObservedAdsorption = flowBasisDiagnostics.observed_last_cycle_schell_si_adsorption_moles_by_component;
summaryOldRatio = flowBasisDiagnostics.old_unconverted_target_observed_to_expected_ratio;
assertClose(summaryExpectedAdsorption, expectedAdsorption, 1e-12, ...
    "summary expected source adsorption inventory");
assertClose(summaryObservedAdsorption, ...
    si.adsorption_feed_input_moles_by_component, 1e-12, ...
    "summary observed Schell SI adsorption inventory");
assert(all(summaryOldRatio < 0.10), ...
    "test_schell_si_accounting:summaryOldFlowBasisNotRejected", ...
    "Summary diagnostics must show the old direct-20 interpretation fails decisively.");

assertCentralSourceTargetsUnchanged(sourcePack, caseId);

fprintf("Tier 3 sanity passed: Schell SI accounting is conserved, bounded, and distinctly labelled.\n");

function assertCentralSourceTargetsUnchanged(sourcePack, caseId)
    caseIds = string({sourcePack.cycle_cases.case_id});
    matches = caseIds == caseId;
    assert(nnz(matches) == 1, ...
        "test_schell_si_accounting:centralCaseMissing", ...
        "Source pack must contain exactly one central Schell performance case.");
    central = sourcePack.cycle_cases(matches);

    assertClose(central.h2_purity_pct, 93.4, 1e-12, ...
        "central h2_purity_pct source target");
    assertClose(central.h2_recovery_pct, 74.4, 1e-12, ...
        "central h2_recovery_pct source target");
    assertClose(central.co2_purity_pct, 78.7, 1e-12, ...
        "central co2_purity_pct source target");
    assertClose(central.co2_recovery_pct, 94.8, 1e-12, ...
        "central co2_recovery_pct source target");
    assert(contains(sourcePack.validation_policy.soft_performance_band_policy, ...
            "report-only at first"), ...
        "test_schell_si_accounting:validationPolicyChanged", ...
        "Schell validation band policy must remain report-only.");
end

function assertPurgeUsesEquimolarFeedTank(si)
    records = si.column_records;
    stepNames = string({records.step_name});
    purgeRecords = records(stepNames == "HP-ATM-FEE");
    assert(~isempty(purgeRecords), ...
        "test_schell_si_accounting:missingPurgeRecords", ...
        "Schell SI records must include HP-ATM-FEE purge records.");

    for i = 1:numel(purgeRecords)
        purgeInput = purgeRecords(i).purge_input_moles_by_component;
        feedTankSource = purgeRecords(i) ...
            .feed_tank_external_feed_moles_by_component;
        productBoundary = purgeRecords(i) ...
            .product_end_boundary_moles_by_component;

        assert(sum(purgeInput) > 1e-8, ...
            "test_schell_si_accounting:zeroPurgeInput", ...
            "HP-ATM-FEE purge records must have nonzero purge input.");
        assert(all(productBoundary < 0), ...
            "test_schell_si_accounting:purgeNotProductEndInlet", ...
            "HP-ATM-FEE purge must enter through the product-end boundary.");
        assertClose(feedTankSource, purgeInput, 1e-8, ...
            "HP-ATM-FEE feed-tank source attribution");
        assertClose(purgeInput(1), purgeInput(2), 1e-8, ...
            "HP-ATM-FEE equimolar purge source");
    end
end

function assertClose(actual, expected, tolerance, context)
    assert(isnumeric(actual), ...
        "test_schell_si_accounting:expectedNumeric", ...
        "Expected numeric value at %s.", context);
    actual = double(actual);
    expected = double(expected);
    assert(isequal(size(actual), size(expected)), ...
        "test_schell_si_accounting:sizeMismatch", ...
        "%s expected size %s, got %s.", context, ...
        mat2str(size(expected)), mat2str(size(actual)));
    if any(abs(actual - expected) > tolerance, "all")
        error("test_schell_si_accounting:numericMismatch", ...
            "%s expected %s, got %s.", context, ...
            mat2str(expected, 16), mat2str(actual, 16));
    end
end
