% Tier 3 one-step physical-sanity scaffold test for Schell route B.
% Failure mode caught: source-pack traceability loss, route drift, missing
% central-case fields, source/native component-role mapping drift,
% flow-unit conversion mistakes, or silently claiming runPsaCycle readiness
% before the SCHELL-08 health runner exists.

repoRoot = fileparts(fileparts(mfilename("fullpath")));
sourcePackPath = fullfile(repoRoot, "params", "schell2013_ap360_sips_binary", ...
    "schell_2013_source_pack.json");

fprintf("Tier 3 sanity: checking Schell route-B case scaffold.\n");

scaffold = build_schell_params_from_source_pack();
sourcePack = jsondecode(fileread(sourcePackPath));

assert(scaffold.route == "B_json_to_params_runPsaCycle", ...
    "test_schell_case_scaffold:wrongRoute", ...
    "Schell scaffold must preserve route B from SCHELL-05.");
assert(scaffold.model_mode == "topsail_native", ...
    "test_schell_case_scaffold:wrongModelMode", ...
    "Schell scaffold must use topsail_native model mode.");
assert(scaffold.run_entrypoint == "runPsaCycle(params)", ...
    "test_schell_case_scaffold:wrongRunEntrypoint", ...
    "Schell scaffold must identify runPsaCycle(params) as the future entry point.");
assert(scaffold.isotherm_route_ready == true, ...
    "test_schell_case_scaffold:isothermRouteNotReady", ...
    "Schell scaffold must mark the optional core Sips route as ready.");
assert(scaffold.run_ready == false, ...
    "test_schell_case_scaffold:prematureHealthRunReady", ...
    "Schell scaffold must not claim health-run readiness before SCHELL-08.");
assert(~any(scaffold.blocking_unresolved_assumption_ids == "SIPS_CORE_INTEGRATION"), ...
    "test_schell_case_scaffold:staleSipsBlocker", ...
    "Schell scaffold must remove SIPS_CORE_INTEGRATION as a route blocker.");

assert(strlength(scaffold.source_pack_sha256) == 64, ...
    "test_schell_case_scaffold:badSourceHash", ...
    "Schell scaffold must record a SHA256 source-pack hash.");

params = scaffold.params;
assert(params.case_id == "schell_20bar_tads40_performance_central", ...
    "test_schell_case_scaffold:wrongDefaultCase", ...
    "Schell scaffold must default to the central 20 bar, 40 s case.");
assert(params.modSp_isotherm_selector == 7, ...
    "test_schell_case_scaffold:wrongIsothermSelector", ...
    "Schell scaffold must select optional core Sips with modSp(1) == 7.");
assert(params.nCycles_requested == 1, ...
    "test_schell_case_scaffold:wrongCycleCount", ...
    "First Schell scaffold must request one health-run cycle only.");
assert(params.nCols == 2 && params.nComs == 2, ...
    "test_schell_case_scaffold:wrongSystemSize", ...
    "Schell scaffold must represent a two-bed binary PSA case.");
assertSchellComponentMapping(params);
assertClose(params.feed.mole_fraction, [0.5; 0.5], 1e-12, ...
    "feed.mole_fraction");
assertClose(sum(params.feed.mole_fraction), 1.0, 1e-12, ...
    "sum(feed.mole_fraction)");
assertSchellNativeVectors(params);

assertClose(params.geometry.column_length_m, 1.2, 1e-12, ...
    "geometry.column_length_m");
assertClose(params.geometry.internal_radius_m, 0.0125, 1e-12, ...
    "geometry.internal_radius_m");
assertClose(params.bed_and_adsorbent.bed_density_kg_per_m3, 480.0, 1e-12, ...
    "bed_and_adsorbent.bed_density_kg_per_m3");

assertClose(params.pressure.low_Pa, 100000.0, 1e-9, ...
    "pressure.low_Pa");
assertClose(params.pressure.high_Pa, 2000000.0, 1e-7, ...
    "pressure.high_Pa");
assert(params.pressure.equalization_policy == "topsail_native_no_source_table_p_peq", ...
    "test_schell_case_scaffold:wrongPeqPolicy", ...
    "Schell scaffold must not invent p_peq.");

assertClose(params.step_times_s.pressurization, 24.0, 1e-12, ...
    "step_times_s.pressurization");
assertClose(params.step_times_s.adsorption, 40.0, 1e-12, ...
    "step_times_s.adsorption");
assertClose(params.step_times_s.pressure_equalization, 3.0, 1e-12, ...
    "step_times_s.pressure_equalization");
assertClose(params.step_times_s.blowdown, 50.0, 1e-12, ...
    "step_times_s.blowdown");
assertClose(params.step_times_s.purge, 15.0, 1e-12, ...
    "step_times_s.purge");

expectedAdsFlow = sourcePack.feed_and_process.flow_rate_conversion_basis ...
    .examples_mol_per_s_at_298p15K.x20_cm3_per_s_at_20_bar;
expectedPurgeFlow = sourcePack.feed_and_process.flow_rate_conversion_basis ...
    .examples_mol_per_s_at_298p15K.x50_cm3_per_s_at_1_bar;
assertClose(params.flow.adsorption_mol_per_s_at_high_pressure, expectedAdsFlow, ...
    1e-14, "flow.adsorption_mol_per_s_at_high_pressure");
assertClose(params.flow.purge_mol_per_s_at_low_pressure, expectedPurgeFlow, ...
    1e-14, "flow.purge_mol_per_s_at_low_pressure");

assert(params.isotherm.model_name == "competitive_temperature_dependent_sips", ...
    "test_schell_case_scaffold:wrongIsotherm", ...
    "Schell scaffold must preserve the source Sips isotherm name.");
assert(params.isotherm.selector == 7, ...
    "test_schell_case_scaffold:wrongNestedIsothermSelector", ...
    "Schell scaffold must record the optional core Sips selector.");
assert(params.isotherm.core_integration_status == ...
    "ready_optional_nondefault_core_sips", ...
    "test_schell_case_scaffold:missingSipsStatus", ...
    "Schell scaffold must mark Sips core integration as ready.");
assert(params.isotherm.do_not_substitute == ...
    "native_extended_langmuir_freundlich_is_not_schell_sips", ...
    "test_schell_case_scaffold:sipsSubstitutionRisk", ...
    "Schell scaffold must not treat native extended Langmuir-Freundlich as Schell Sips.");
assertSchellSipsArrays(params, sourcePack.isotherm.parameters);

assert(endsWith(scaffold.summary.expected_output_path, ...
    fullfile("validation", "reports", "schell_2013", "health", ...
    "schell_20bar_tads40_performance_central_summary.json")), ...
    "test_schell_case_scaffold:wrongSummaryPath", ...
    "Schell scaffold must expose the expected health summary path.");
assertSchell08RunsHealth(repoRoot);

fprintf("Tier 3 sanity passed: Schell case scaffold is traceable and inspectable.\n");

function assertClose(actual, expected, tolerance, context)
    assert(isnumeric(actual), ...
        "test_schell_case_scaffold:expectedNumeric", ...
        "Expected numeric value at %s.", context);
    actual = double(actual);
    expected = double(expected);
    assert(isequal(size(actual), size(expected)), ...
        "test_schell_case_scaffold:sizeMismatch", ...
        "%s expected size %s, got %s.", context, ...
        mat2str(size(expected)), mat2str(size(actual)));
    if any(abs(actual - expected) > tolerance, "all")
        error("test_schell_case_scaffold:numericMismatch", ...
            "%s expected %s, got %s.", context, ...
            mat2str(expected, 16), mat2str(actual, 16));
    end
end

function assertSchellComponentMapping(params)
    assert(isequal(params.component_order.source, ["CO2"; "H2"]), ...
        "test_schell_case_scaffold:wrongSourceComponentOrder", ...
        "Schell scaffold must preserve source component order as CO2/H2.");
    assert(isequal(params.component_order.topsail_native, ["H2"; "CO2"]), ...
        "test_schell_case_scaffold:wrongNativeComponentOrder", ...
        "Schell scaffold must use H2/CO2 toPSAil-native runtime order.");
    assert(isequal(params.components, ["H2"; "CO2"]), ...
        "test_schell_case_scaffold:wrongComponents", ...
        "Schell scaffold runtime components must use toPSAil-native order.");
    assert(params.nLKs == 1, ...
        "test_schell_case_scaffold:wrongLightKeyCount", ...
        "Schell runtime params must identify one light-key raffinate component.");
    assert(isequal(params.component_mapping.topsail_native_to_source_index, [2; 1]), ...
        "test_schell_case_scaffold:wrongNativeToSourceMap", ...
        "Schell native-to-source component map must convert H2/CO2 to CO2/H2.");
    assert(isequal(params.component_mapping.source_to_topsail_native_index, [2; 1]), ...
        "test_schell_case_scaffold:wrongSourceToNativeMap", ...
        "Schell source-to-native component map must convert CO2/H2 to H2/CO2.");
    assert(params.component_roles.light_product == "H2", ...
        "test_schell_case_scaffold:wrongLightProduct", ...
        "Schell light product must be H2.");
    assert(params.component_roles.heavy_product == "CO2", ...
        "test_schell_case_scaffold:wrongHeavyProduct", ...
        "Schell heavy product must be CO2.");
    assert(params.component_roles.raffinate_product == "H2", ...
        "test_schell_case_scaffold:wrongRaffinateProduct", ...
        "Schell raffinate product must be H2.");
    assert(params.component_roles.extract_product == "CO2", ...
        "test_schell_case_scaffold:wrongExtractProduct", ...
        "Schell extract product must be CO2.");
end

function assertSchellNativeVectors(params)
    assertClose(params.topsail_native_vectors.ldf_rate_per_s, ...
        [1.0, 0.15], 1e-12, ...
        "topsail_native_vectors.ldf_rate_per_s");
    assertClose(params.topsail_native_vectors.gas_heat_capacity_J_per_mol_K, ...
        [29.0, 42.5], 1e-12, ...
        "topsail_native_vectors.gas_heat_capacity_J_per_mol_K");
    assertClose(params.topsail_native_vectors.heat_of_adsorption_J_per_mol, ...
        [-9800.0, -21000.0], 1e-12, ...
        "topsail_native_vectors.heat_of_adsorption_J_per_mol");
    assertClose(params.isotherm.heat_of_adsorption_J_per_mol, ...
        params.topsail_native_vectors.heat_of_adsorption_J_per_mol, 1e-12, ...
        "isotherm.heat_of_adsorption_J_per_mol");
    assert(params.isotherm.parameters_component_order == "source", ...
        "test_schell_case_scaffold:wrongIsothermParameterOrder", ...
        "Schell source-facing isotherm parameters must remain in source form.");
    assert(isequal(params.isotherm.topsail_native_component_order, ["H2"; "CO2"]), ...
        "test_schell_case_scaffold:wrongIsothermNativeOrder", ...
        "Schell isotherm must expose the H2/CO2 native runtime order.");
end

function assertSchellSipsArrays(params, isoParams)
    assertClose(params.schellSipsNInfA_molPerKg, ...
        [isoParams.H2.a, isoParams.CO2.a], 1e-12, ...
        "schellSipsNInfA_molPerKg");
    assertClose(params.schellSipsNInfB_JPerMol, ...
        [isoParams.H2.b, isoParams.CO2.b], 1e-12, ...
        "schellSipsNInfB_JPerMol");
    assertClose(params.schellSipsAffA_invPa, ...
        [isoParams.H2.A, isoParams.CO2.A], 1e-20, ...
        "schellSipsAffA_invPa");
    assertClose(params.schellSipsAffB_JPerMol, ...
        [isoParams.H2.B, isoParams.CO2.B], 1e-12, ...
        "schellSipsAffB_JPerMol");
    assertClose(params.schellSipsAlpha, ...
        [isoParams.H2.alpha, isoParams.CO2.alpha], 1e-12, ...
        "schellSipsAlpha");
    assertClose(params.schellSipsBeta_invK, ...
        [isoParams.H2.beta, isoParams.CO2.beta], 1e-12, ...
        "schellSipsBeta_invK");
    assertClose(params.schellSipsSref, ...
        [isoParams.H2.sref, isoParams.CO2.sref], 1e-12, ...
        "schellSipsSref");
    assertClose(params.schellSipsTref_K, ...
        [isoParams.H2.Tref, isoParams.CO2.Tref], 1e-12, ...
        "schellSipsTref_K");
end

function assertSchell08RunsHealth(repoRoot)
    taskCardsPath = fullfile(repoRoot, "docs", "workflow", ...
        "schell_2013_implementation", "task_cards.md");
    taskCardsText = string(fileread(taskCardsPath));
    assert(contains(taskCardsText, "run('scripts/run_schell_case_health.m')"), ...
        "test_schell_case_scaffold:schell08MissingHealthRun", ...
        "SCHELL-08 required commands must explicitly run the health script.");
    assert(contains(taskCardsText, "python -m json.tool validation/reports/schell_2013/health/schell_20bar_tads40_performance_central_summary.json > $null"), ...
        "test_schell_case_scaffold:schell08MissingSummaryJsonCheck", ...
        "SCHELL-08 required commands must validate the emitted health summary JSON.");
end
