% Tier 3 one-step physical-sanity scaffold test for Schell route B.
% Failure mode caught: source-pack traceability loss, route drift, missing
% central-case fields, flow-unit conversion mistakes, or silently claiming
% runPsaCycle readiness before the SCHELL-08 health runner exists.

repoRoot = fileparts(fileparts(mfilename("fullpath")));
sourcePackPath = fullfile(repoRoot, "params", "schell2013_ap360_sips_binary", ...
    "schell_2013_source_pack.json");

fprintf("Tier 3 sanity: checking Schell route-B case scaffold.\n");

scaffold = build_schell_params_from_source_pack();
sourcePack = jsondecode(fileread(sourcePackPath));

assert(scaffold.route == "B_json_to_params_runPsaCycle", ...
    "test_schell_case_scaffold:wrongRoute", ...
    "Schell scaffold must preserve route B from SCHELL-05.");
assert(scaffold.model_mode == "topsail_native", ...
    "test_schell_case_scaffold:wrongModelMode", ...
    "Schell scaffold must use topsail_native model mode.");
assert(scaffold.run_entrypoint == "runPsaCycle(params)", ...
    "test_schell_case_scaffold:wrongRunEntrypoint", ...
    "Schell scaffold must identify runPsaCycle(params) as the future entry point.");
assert(scaffold.isotherm_route_ready == true, ...
    "test_schell_case_scaffold:isothermRouteNotReady", ...
    "Schell scaffold must mark the optional core Sips route as ready.");
assert(scaffold.run_ready == false, ...
    "test_schell_case_scaffold:prematureHealthRunReady", ...
    "Schell scaffold must not claim health-run readiness before SCHELL-08.");
assert(~any(scaffold.blocking_unresolved_assumption_ids == "SIPS_CORE_INTEGRATION"), ...
    "test_schell_case_scaffold:staleSipsBlocker", ...
    "Schell scaffold must remove SIPS_CORE_INTEGRATION as a route blocker.");

assert(strlength(scaffold.source_pack_sha256) == 64, ...
    "test_schell_case_scaffold:badSourceHash", ...
    "Schell scaffold must record a SHA256 source-pack hash.");

params = scaffold.params;
assert(params.case_id == "schell_20bar_tads40_performance_central", ...
    "test_schell_case_scaffold:wrongDefaultCase", ...
    "Schell scaffold must default to the central 20 bar, 40 s case.");
assert(params.modSp_isotherm_selector == 7, ...
    "test_schell_case_scaffold:wrongIsothermSelector", ...
    "Schell scaffold must select optional core Sips with modSp(1) == 7.");
assert(params.nCycles_requested == 1, ...
    "test_schell_case_scaffold:wrongCycleCount", ...
    "First Schell scaffold must request one health-run cycle only.");
assert(params.nCols == 2 && params.nComs == 2, ...
    "test_schell_case_scaffold:wrongSystemSize", ...
    "Schell scaffold must represent a two-bed binary PSA case.");
assert(isequal(params.components, ["CO2"; "H2"]), ...
    "test_schell_case_scaffold:wrongComponents", ...
    "Schell scaffold must preserve CO2/H2 component order.");
assertClose(params.feed.mole_fraction, [0.5; 0.5], 1e-12, ...
    "feed.mole_fraction");
assertClose(sum(params.feed.mole_fraction), 1.0, 1e-12, ...
    "sum(feed.mole_fraction)");

assertClose(params.geometry.column_length_m, 1.2, 1e-12, ...
    "geometry.column_length_m");
assertClose(params.geometry.internal_radius_m, 0.0125, 1e-12, ...
    "geometry.internal_radius_m");
assertClose(params.bed_and_adsorbent.bed_density_kg_per_m3, 480.0, 1e-12, ...
    "bed_and_adsorbent.bed_density_kg_per_m3");

assertClose(params.pressure.low_Pa, 100000.0, 1e-9, ...
    "pressure.low_Pa");
assertClose(params.pressure.high_Pa, 2000000.0, 1e-7, ...
    "pressure.high_Pa");
assert(params.pressure.equalization_policy == "topsail_native_no_source_table_p_peq", ...
    "test_schell_case_scaffold:wrongPeqPolicy", ...
    "Schell scaffold must not invent p_peq.");

assertClose(params.step_times_s.pressurization, 24.0, 1e-12, ...
    "step_times_s.pressurization");
assertClose(params.step_times_s.adsorption, 40.0, 1e-12, ...
    "step_times_s.adsorption");
assertClose(params.step_times_s.pressure_equalization, 3.0, 1e-12, ...
    "step_times_s.pressure_equalization");
assertClose(params.step_times_s.blowdown, 50.0, 1e-12, ...
    "step_times_s.blowdown");
assertClose(params.step_times_s.purge, 15.0, 1e-12, ...
    "step_times_s.purge");

expectedAdsFlow = sourcePack.feed_and_process.flow_rate_conversion_basis ...
    .examples_mol_per_s_at_298p15K.x20_cm3_per_s_at_20_bar;
expectedPurgeFlow = sourcePack.feed_and_process.flow_rate_conversion_basis ...
    .examples_mol_per_s_at_298p15K.x50_cm3_per_s_at_1_bar;
assertClose(params.flow.adsorption_mol_per_s_at_high_pressure, expectedAdsFlow, ...
    1e-14, "flow.adsorption_mol_per_s_at_high_pressure");
assertClose(params.flow.purge_mol_per_s_at_low_pressure, expectedPurgeFlow, ...
    1e-14, "flow.purge_mol_per_s_at_low_pressure");

assert(params.isotherm.model_name == "competitive_temperature_dependent_sips", ...
    "test_schell_case_scaffold:wrongIsotherm", ...
    "Schell scaffold must preserve the source Sips isotherm name.");
assert(params.isotherm.selector == 7, ...
    "test_schell_case_scaffold:wrongNestedIsothermSelector", ...
    "Schell scaffold must record the optional core Sips selector.");
assert(params.isotherm.core_integration_status == ...
    "ready_optional_nondefault_core_sips", ...
    "test_schell_case_scaffold:missingSipsStatus", ...
    "Schell scaffold must mark Sips core integration as ready.");
assert(params.isotherm.do_not_substitute == ...
    "native_extended_langmuir_freundlich_is_not_schell_sips", ...
    "test_schell_case_scaffold:sipsSubstitutionRisk", ...
    "Schell scaffold must not treat native extended Langmuir-Freundlich as Schell Sips.");
assertSchellSipsArrays(params, sourcePack.isotherm.parameters);

assert(endsWith(scaffold.summary.expected_output_path, ...
    fullfile("validation", "reports", "schell_2013", "health", ...
    "schell_20bar_tads40_performance_central_summary.json")), ...
    "test_schell_case_scaffold:wrongSummaryPath", ...
    "Schell scaffold must expose the expected health summary path.");

fprintf("Tier 3 sanity passed: Schell case scaffold is traceable and inspectable.\n");

function assertClose(actual, expected, tolerance, context)
    assert(isnumeric(actual), ...
        "test_schell_case_scaffold:expectedNumeric", ...
        "Expected numeric value at %s.", context);
    actual = double(actual);
    expected = double(expected);
    assert(isequal(size(actual), size(expected)), ...
        "test_schell_case_scaffold:sizeMismatch", ...
        "%s expected size %s, got %s.", context, ...
        mat2str(size(expected)), mat2str(size(actual)));
    if any(abs(actual - expected) > tolerance, "all")
        error("test_schell_case_scaffold:numericMismatch", ...
            "%s expected %s, got %s.", context, ...
            mat2str(expected, 16), mat2str(actual, 16));
    end
end

function assertSchellSipsArrays(params, isoParams)
    assertClose(params.schellSipsNInfA_molPerKg, ...
        [isoParams.CO2.a, isoParams.H2.a], 1e-12, ...
        "schellSipsNInfA_molPerKg");
    assertClose(params.schellSipsNInfB_JPerMol, ...
        [isoParams.CO2.b, isoParams.H2.b], 1e-12, ...
        "schellSipsNInfB_JPerMol");
    assertClose(params.schellSipsAffA_invPa, ...
        [isoParams.CO2.A, isoParams.H2.A], 1e-20, ...
        "schellSipsAffA_invPa");
    assertClose(params.schellSipsAffB_JPerMol, ...
        [isoParams.CO2.B, isoParams.H2.B], 1e-12, ...
        "schellSipsAffB_JPerMol");
    assertClose(params.schellSipsAlpha, ...
        [isoParams.CO2.alpha, isoParams.H2.alpha], 1e-12, ...
        "schellSipsAlpha");
    assertClose(params.schellSipsBeta_invK, ...
        [isoParams.CO2.beta, isoParams.H2.beta], 1e-12, ...
        "schellSipsBeta_invK");
    assertClose(params.schellSipsSref, ...
        [isoParams.CO2.sref, isoParams.H2.sref], 1e-12, ...
        "schellSipsSref");
    assertClose(params.schellSipsTref_K, ...
        [isoParams.CO2.Tref, isoParams.H2.Tref], 1e-12, ...
        "schellSipsTref_K");
end
