function rows = appendYangBedInventoryDeltaRows(group, initialInventory, terminalInventory, controls, varargin)
%APPENDYANGBEDINVENTORYDELTAROWS Create bed-inventory delta ledger rows.

    if nargin < 4 || isempty(controls)
        controls = struct("componentNames", ["H2"; "CO2"]);
    end

    parser = inputParser;
    addParameter(parser, 'CycleIndex', NaN);
    addParameter(parser, 'ComponentNames', getControlField(controls, 'componentNames', ["H2"; "CO2"]));
    parse(parser, varargin{:});
    opts = parser.Results;

    componentNames = string(opts.ComponentNames(:));
    tmpLedger = makeYangFourBedLedger(componentNames, ...
        'LedgerNote', "FI-7 inventory delta temporary ledger");
    localMap = group.localMap;

    for i = 1:height(localMap)
        bed = string(localMap.global_bed(i));
        fieldName = matlab.lang.makeValidName("bed_" + bed);
        if ~isfield(initialInventory, fieldName) || ~isfield(terminalInventory, fieldName)
            error('FI7:MissingInventoryDelta', ...
                'Missing initial or terminal inventory for bed %s.', char(bed));
        end

        [delta, basis, units] = inventoryDelta(initialInventory.(fieldName), ...
            terminalInventory.(fieldName));
        tmpLedger = appendYangLedgerStreamRows(tmpLedger, componentNames, delta, ...
            'CycleIndex', opts.CycleIndex, ...
            'SlotIndex', group.sourceCol, ...
            'OperationGroupId', string(group.operationGroupId), ...
            'SourceCol', group.sourceCol, ...
            'RecordId', string(localMap.record_id(i)), ...
            'PairId', string(group.pairId), ...
            'StageLabel', string(group.stageLabel), ...
            'DirectTransferFamily', string(group.directTransferFamily), ...
            'YangLabel', string(localMap.yang_label(i)), ...
            'GlobalBed', bed, ...
            'LocalIndex', localMap.local_index(i), ...
            'LocalRole', string(localMap.local_role(i)), ...
            'StreamScope', "bed_inventory_delta", ...
            'StreamDirection', "delta", ...
            'Endpoint', "not_applicable", ...
            'Basis', basis, ...
            'Units', units, ...
            'Notes', "terminal inventory minus initial inventory", ...
            'AllowSignedMoles', true);
    end

    rows = tmpLedger.streamRows;
end

function [delta, basis, units] = inventoryDelta(initial, terminal)
    if isfield(initial, 'usedPhysicalMoles') && initial.usedPhysicalMoles && ...
            isfield(terminal, 'usedPhysicalMoles') && terminal.usedPhysicalMoles && ...
            isfield(initial, 'moles') && isfield(terminal, 'moles') && ...
            ~isempty(initial.moles.totalByComponent) && ~isempty(terminal.moles.totalByComponent)
        delta = terminal.moles.totalByComponent(:) - initial.moles.totalByComponent(:);
        basis = "physical_moles_from_available_scale_factors";
        units = "mol";
    else
        delta = terminal.native.totalByComponent(:) - initial.native.totalByComponent(:);
        basis = "native_column_balance_scaled_inventory";
        units = "native_inventory_units";
    end
end

function value = getControlField(s, name, defaultValue)
    value = defaultValue;
    if isstruct(s) && isfield(s, name) && ~isempty(s.(name))
        value = s.(name);
    end
end
