function ledger = makeYangFourBedLedger(componentNames, varargin)
%MAKEYANGFOURBEDLEDGER Create an empty WP5 component-resolved ledger.

    componentNames = normalizeComponentNames(componentNames);

    parser = inputParser;
    addParameter(parser, 'Manifest', []);
    addParameter(parser, 'PairMap', []);
    addParameter(parser, 'Metadata', []);
    addParameter(parser, 'LedgerNote', "not_supplied");
    parse(parser, varargin{:});
    opts = parser.Results;

    manifest = opts.Manifest;
    pairMap = opts.PairMap;
    if isempty(manifest)
        manifest = getYangFourBedScheduleManifest();
    end
    if isempty(pairMap)
        pairMap = getYangDirectTransferPairMap(manifest);
    end

    metadata = opts.Metadata;
    if isempty(metadata)
        metadata = makeYangFourBedRunMetadata(manifest, pairMap, ...
            'Notes', string(opts.LedgerNote));
    end

    ledger = struct();
    ledger.version = "WP5-Yang2009-four-bed-ledger-v1";
    ledger.componentNames = componentNames(:);
    ledger.streamRows = makeEmptyStreamRows();
    ledger.balanceRows = makeEmptyBalanceRows();
    ledger.metricRows = makeEmptyMetricRows();
    ledger.cssRows = makeEmptyCssRows();
    ledger.metadata = metadata;
    ledger.architecture = struct( ...
        "noDynamicInternalTanks", true, ...
        "noSharedHeaderInventory", true, ...
        "noFourBedRhsDae", true, ...
        "noCoreAdsorberPhysicsRewrite", true, ...
        "wp5AccountingLayerOnly", true, ...
        "internalTransfersCountAsExternalProduct", false);

    result = validateYangFourBedLedger(ledger);
    if ~result.pass
        error('WP5:InvalidLedger', ...
            'Empty Yang four-bed ledger failed validation: %s', ...
            char(strjoin(result.failures, " | ")));
    end
end

function componentNames = normalizeComponentNames(componentNames)
    if nargin < 1 || isempty(componentNames)
        error('WP5:InvalidComponentNames', ...
            'componentNames must be a nonempty string or cell array.');
    end
    componentNames = string(componentNames(:));
    if any(strlength(componentNames) == 0) || numel(unique(componentNames)) ~= numel(componentNames)
        error('WP5:InvalidComponentNames', ...
            'componentNames must be nonempty and unique.');
    end
end

function rows = makeEmptyStreamRows()
    rows = table( ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        strings(0, 1), ...
        nan(0, 1), ...
        strings(0, 1), ...
        strings(0, 1), ...
        strings(0, 1), ...
        strings(0, 1), ...
        strings(0, 1), ...
        strings(0, 1), ...
        nan(0, 1), ...
        strings(0, 1), ...
        strings(0, 1), ...
        strings(0, 1), ...
        strings(0, 1), ...
        strings(0, 1), ...
        zeros(0, 1), ...
        strings(0, 1), ...
        strings(0, 1), ...
        strings(0, 1), ...
        'VariableNames', [
            "cycle_index"
            "slot_index"
            "operation_group_id"
            "source_col"
            "record_id"
            "pair_id"
            "stage_label"
            "direct_transfer_family"
            "yang_label"
            "global_bed"
            "local_index"
            "local_role"
            "stream_scope"
            "stream_direction"
            "endpoint"
            "component"
            "moles"
            "basis"
            "units"
            "notes"
        ]);
end

function rows = makeEmptyBalanceRows()
    rows = table( ...
        zeros(0, 1), ...
        nan(0, 1), ...
        strings(0, 1), ...
        strings(0, 1), ...
        strings(0, 1), ...
        strings(0, 1), ...
        strings(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        false(0, 1), ...
        strings(0, 1), ...
        strings(0, 1), ...
        'VariableNames', [
            "cycle_index"
            "slot_index"
            "balance_scope"
            "operation_group_id"
            "stage_label"
            "direct_transfer_family"
            "component"
            "external_feed_moles"
            "external_product_moles"
            "external_waste_moles"
            "bed_inventory_delta_moles"
            "internal_out_of_donor_moles"
            "internal_into_receiver_moles"
            "residual_moles"
            "tolerance_moles"
            "pass"
            "basis"
            "notes"
        ]);
end

function rows = makeEmptyMetricRows()
    rows = table( ...
        zeros(0, 1), ...
        strings(0, 1), ...
        strings(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        strings(0, 1), ...
        false(0, 1), ...
        strings(0, 1), ...
        'VariableNames', [
            "cycle_index"
            "metric_name"
            "component"
            "value"
            "numerator_moles"
            "denominator_moles"
            "basis"
            "pass"
            "notes"
        ]);
end

function rows = makeEmptyCssRows()
    rows = table( ...
        zeros(0, 1), ...
        strings(0, 1), ...
        strings(0, 1), ...
        strings(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        false(0, 1), ...
        strings(0, 1), ...
        'VariableNames', [
            "cycle_index"
            "bed"
            "state_field"
            "family"
            "n_values"
            "max_abs"
            "rms_abs"
            "relative_norm"
            "pass"
            "notes"
        ]);
end
