function terminalLocalStates = extractYangTerminalLocalStates(params, stStates, tempCase)
%EXTRACTYANGTERMINALLOCALSTATES Return terminal adsorber states in local order.

    result = validateYangTemporaryCase(tempCase);
    if ~result.pass
        error('WP4:InvalidTemporaryCase', ...
            'Cannot extract terminal states from an invalid temporary case.');
    end

    if nargin < 1 || ~isstruct(params) || ~isfield(params, 'nColStT')
        error('WP4:InvalidTemplateParams', ...
            'Params must include nColStT for terminal state extraction.');
    end

    if nargin < 2 || ~isnumeric(stStates) || isempty(stStates)
        error('WP4:InvalidStateHistory', ...
            'stStates must be a nonempty numeric state-history matrix.');
    end

    termStates = convert2TermStates(params, stStates);
    terminalLocalStates = cell(tempCase.nLocalBeds, 1);
    for i = 1:tempCase.nLocalBeds
        localStateVector = convert2ColStates(params, termStates, i);
        terminalLocalStates{i} = struct( ...
            "payloadType", "toPSAil_adsorber_state_v1", ...
            "stateVector", localStateVector, ...
            "metadata", struct( ...
                "source", "WP4 temporary case", ...
                "globalBed", string(tempCase.localMap.global_bed(i)), ...
                "localIndex", tempCase.localMap.local_index(i), ...
                "yangLabel", string(tempCase.localMap.yang_label(i)), ...
                "pairId", string(tempCase.pairId), ...
                "directTransferFamily", string(tempCase.directTransferFamily)));
    end
end
