function result = validateYangFourBedScheduleManifest(manifest)
%VALIDATEYANGFOURBEDSCHEDULEMANIFEST Static WP1 integrity checks.

    failures = strings(0, 1);
    warnings = strings(0, 1);
    checks = table(strings(0, 1), false(0, 1), strings(0, 1), ...
        'VariableNames', ["check", "passed", "detail"]);

    if nargin < 1 || ~isstruct(manifest)
        recordCheck("manifest_is_struct", false, "Manifest input must be a struct.");
        result = packResult();
        return;
    end

    requiredFields = [
        "version"
        "sourceName"
        "bedLabels"
        "architecture"
        "duration"
        "sourceColumns"
        "bedSteps"
        "labelGlossary"
        "pressureClasses"
        "layeredBedAudit"
    ];

    manifestFields = string(fieldnames(manifest));
    for i = 1:numel(requiredFields)
        fieldName = requiredFields(i);
        recordCheck("has_field_" + fieldName, any(manifestFields == fieldName), ...
            "Required manifest top-level field.");
    end

    if ~all(ismember(requiredFields, manifestFields))
        result = packResult();
        return;
    end

    sourceColumns = manifest.sourceColumns;
    bedSteps = manifest.bedSteps;
    glossary = manifest.labelGlossary;
    pressureClasses = manifest.pressureClasses;

    recordCheck("version_nonempty", strlength(string(manifest.version)) > 0, ...
        "Manifest version must be nonempty.");
    recordCheck("source_name_nonempty", strlength(string(manifest.sourceName)) > 0, ...
        "Manifest source name must be nonempty.");
    recordCheck("bed_labels_are_A_B_C_D", isequal(string(manifest.bedLabels), ["A", "B", "C", "D"]), ...
        "Bed labels must be exactly A, B, C, D.");
    recordCheck("source_columns_row_count", istable(sourceColumns) && height(sourceColumns) == 10, ...
        "Source columns table must have ten rows.");
    recordCheck("bed_steps_row_count", istable(bedSteps) && height(bedSteps) == 40, ...
        "Bed steps table must have forty rows.");

    sourceLabelVars = ["bed_A_label", "bed_B_label", "bed_C_label", "bed_D_label"];
    recordCheck("source_columns_all_beds_present", ...
        all(ismember(sourceLabelVars, string(sourceColumns.Properties.VariableNames))) && ...
        all(strlength(sourceColumns{:, sourceLabelVars}) > 0, "all"), ...
        "Every source column must have labels for all four beds.");

    expected = struct();
    expected.A = ["AD"; "AD&PP"; "EQI-BD"; "PP"; "EQII-BD"; "BD"; "PU"; "EQII-PR"; "EQI-PR"; "BF"];
    expected.B = ["EQI-PR"; "BF"; "AD"; "AD&PP"; "EQI-BD"; "PP"; "EQII-BD"; "BD"; "PU"; "EQII-PR"];
    expected.C = ["BD"; "PU"; "EQII-PR"; "EQI-PR"; "BF"; "AD"; "AD&PP"; "EQI-BD"; "PP"; "EQII-BD"];
    expected.D = ["EQI-BD"; "PP"; "EQII-BD"; "BD"; "PU"; "EQII-PR"; "EQI-PR"; "BF"; "AD"; "AD&PP"];

    for bedLabel = ["A", "B", "C", "D"]
        rows = bedSteps(bedSteps.bed == bedLabel, :);
        [~, order] = sort(rows.bed_step_index);
        seq = rows.yang_label(order);
        recordCheck("bed_" + bedLabel + "_has_ten_steps", ...
            height(rows) == 10 && isequal(sort(rows.bed_step_index), (1:10)'), ...
            "Each named bed must have ten ordered step indices.");
        recordCheck("bed_" + bedLabel + "_sequence_matches_yang", ...
            isequal(seq, expected.(char(bedLabel))), ...
            "Named bed sequence must match Yang Table 2.");
    end

    recordCheck("all_labels_in_glossary", ...
        all(ismember(bedSteps.yang_label, glossary.yang_label)), ...
        "Every bed-step label must appear in the label glossary.");
    recordCheck("glossary_pressure_metadata_nonempty", ...
        all(strlength(glossary.pressure_mode) > 0) && ...
        all(strlength(glossary.p_start_class) > 0) && ...
        all(strlength(glossary.p_end_class) > 0), ...
        "Every label must have pressure metadata.");

    parsedDurations = arrayfun(@parseYangDurationLabel, sourceColumns.duration_label_raw);
    recordCheck("duration_labels_parse_to_units", ...
        isequal(parsedDurations(:), sourceColumns.duration_units_t24), ...
        "Every raw duration label must parse to the stored t_c/24 units.");
    recordCheck("raw_duration_units_sum_25", ...
        sum(sourceColumns.duration_units_t24) == 25, ...
        "Raw displayed duration units must sum to 25.");
    recordCheck("duration_raw_units_per_displayed_cycle", ...
        manifest.duration.rawUnitsPerDisplayedCycle == 25, ...
        "Duration metadata must expose 25 raw units per displayed cycle.");
    recordCheck("duration_raw_fraction_of_tc", ...
        abs(manifest.duration.rawSumFractionOfTc - 25/24) < 1e-12, ...
        "Duration metadata must expose 25/24 raw fraction of t_c.");
    recordCheck("normalized_fractions_sum_to_one", ...
        abs(sum(sourceColumns.normalized_fraction_of_displayed_cycle) - 1) < 1e-12, ...
        "Normalized displayed-cycle fractions must sum to one.");
    durationFields = string(fieldnames(manifest.duration));
    hasExecutableUnits = any(durationFields == "executableUnits");
    hasExecutableFractions = any(durationFields == "executableFractions");
    hasExecutableUnitsPerCycle = any(durationFields == "executableUnitsPerCycle");
    hasNormalizationPolicy = any(durationFields == "normalizationPolicy");
    hasCycleTimeMappingPolicy = any(durationFields == "cycleTimeMappingPolicy");
    hasRawFractionPolicy = any(durationFields == "rawFractionPolicy");
    expectedDurationUnits = [1; 6; 1; 4; 1; 1; 4; 1; 1; 5];
    recordCheck("duration_executable_units_present", ...
        hasExecutableUnits && isequal(manifest.duration.executableUnits(:), expectedDurationUnits), ...
        "Duration metadata must expose executable displayed units [1,6,1,4,1,1,4,1,1,5].");
    recordCheck("duration_executable_units_per_cycle_25", ...
        hasExecutableUnitsPerCycle && manifest.duration.executableUnitsPerCycle == 25, ...
        "Executable duration units must be normalized over 25 units.");
    recordCheck("duration_executable_fractions_present", ...
        hasExecutableFractions && ...
        isequal(manifest.duration.executableFractions(:), expectedDurationUnits ./ 25), ...
        "Duration metadata must expose executable fractions equal to units/25.");
    recordCheck("duration_executable_fractions_sum_to_one", ...
        hasExecutableFractions && abs(sum(manifest.duration.executableFractions(:)) - 1) < 1e-12, ...
        "Executable duration fractions must sum to one.");
    recordCheck("duration_policy_normalized_over_25", ...
        hasNormalizationPolicy && ...
        contains(string(manifest.duration.normalizationPolicy), "over_25"), ...
        "Duration normalization policy must explicitly state execution over 25 units.");
    recordCheck("cycle_time_policy_uses_executable_fractions", ...
        hasCycleTimeMappingPolicy && ...
        contains(string(manifest.duration.cycleTimeMappingPolicy), "cycleTimeSec") && ...
        contains(string(manifest.duration.cycleTimeMappingPolicy), "executableFractions") && ...
        ~contains(string(manifest.duration.cycleTimeMappingPolicy), "/24"), ...
        "Cycle-time mapping must use executable fractions, not the raw 24-unit basis.");
    recordCheck("raw_fraction_policy_metadata_only", ...
        hasRawFractionPolicy && contains(string(manifest.duration.rawFractionPolicy), "metadata_only"), ...
        "Raw 25/24 fraction must be marked as metadata only.");
    sourceColumnVars = string(sourceColumns.Properties.VariableNames);
    recordCheck("source_columns_executable_fraction_present", ...
        ismember("executable_duration_fraction", sourceColumnVars) && ...
        abs(sum(sourceColumns.executable_duration_fraction) - 1) < 1e-12 && ...
        isequal(sourceColumns.executable_duration_fraction(:), expectedDurationUnits ./ 25), ...
        "Source columns must expose executable normalized duration fractions.");
    bedStepVars = string(bedSteps.Properties.VariableNames);
    recordCheck("bed_steps_executable_fraction_present", ...
        ismember("executable_duration_fraction", bedStepVars) && ...
        all(bedSteps.executable_duration_fraction == bedSteps.normalized_fraction_of_displayed_cycle), ...
        "Bed steps must carry executable normalized duration fractions for later wrapper calls.");

    forbiddenPartnerVars = [
        "partner_bed"
        "paired_with"
        "donor_bed"
        "receiver_bed"
        "partnerBed"
        "pairedWith"
        "donorBed"
        "receiverBed"
    ];
    badPartnerVars = intersect(lower(string(bedSteps.Properties.VariableNames)), lower(forbiddenPartnerVars));
    recordCheck("wp1_has_no_partner_identity_fields", isempty(badPartnerVars), ...
        "WP1 must not assign pair partner identities.");

    directRows = bedSteps.direct_transfer_family ~= "none";
    recordCheck("direct_transfer_rows_require_pair_map", ...
        all(bedSteps.requires_pair_map(directRows)), ...
        "Every direct-transfer operation must require the WP2 pair map.");
    recordCheck("adpp_marked_compound", ...
        all(bedSteps.is_compound(bedSteps.yang_label == "AD&PP")) && ...
        glossary.is_compound(glossary.yang_label == "AD&PP"), ...
        "AD&PP must remain a compound operation.");
    recordCheck("eqi_and_eqii_distinct", ...
        any(bedSteps.direct_transfer_family == "EQI") && ...
        any(bedSteps.direct_transfer_family == "EQII"), ...
        "EQI and EQII must remain distinct direct-transfer families.");

    pressureClassLabels = pressureClasses.pressure_class;
    recordCheck("bed_step_pressure_classes_defined", ...
        all(ismember(bedSteps.p_start_class, pressureClassLabels)) && ...
        all(ismember(bedSteps.p_end_class, pressureClassLabels)), ...
        "Every bed-step pressure class must be present in pressure metadata.");
    intermediate = ismember(pressureClassLabels, ["P1", "P2", "P3", "P5", "P6"]);
    recordCheck("intermediate_pressures_are_symbolic", ...
        all(isnan(pressureClasses.numeric_value(intermediate))), ...
        "WP1 must not invent numeric intermediate pressure values.");
    recordCheck("pressure_anchors_match_source", ...
        pressureClasses.numeric_value(pressureClassLabels == "PF") == 9.0 && ...
        pressureClasses.numeric_value(pressureClassLabels == "P4") == 1.3, ...
        "WP1 pressure anchors must be PF=9 atm and P4=1.3 atm.");

    arch = manifest.architecture;
    recordCheck("architecture_no_dynamic_tanks", ...
        isfield(arch, "noDynamicInternalTanks") && arch.noDynamicInternalTanks, ...
        "Architecture must forbid dynamic internal tanks.");
    recordCheck("architecture_no_shared_header", ...
        isfield(arch, "noSharedHeaderInventory") && arch.noSharedHeaderInventory, ...
        "Architecture must forbid shared header inventory.");
    recordCheck("architecture_no_four_bed_rhs", ...
        isfield(arch, "noFourBedRhsDae") && arch.noFourBedRhsDae, ...
        "Architecture must forbid a global four-bed RHS/DAE.");
    recordCheck("architecture_no_core_physics_rewrite", ...
        isfield(arch, "noCoreAdsorberPhysicsRewrite") && arch.noCoreAdsorberPhysicsRewrite, ...
        "Architecture must preserve core adsorber physics.");
    recordCheck("architecture_wp1_no_pair_identities", ...
        isfield(arch, "wp1DefinesPairIdentities") && ~arch.wp1DefinesPairIdentities, ...
        "WP1 must explicitly avoid defining pair identities.");

    forbiddenStateVars = [
        "tank_state"
        "header_inventory"
        "shared_header_inventory"
        "dynamic_tank_inventory"
        "four_bed_state_vector"
    ];
    allTableVars = [
        string(sourceColumns.Properties.VariableNames), ...
        string(bedSteps.Properties.VariableNames), ...
        string(glossary.Properties.VariableNames), ...
        string(pressureClasses.Properties.VariableNames)
    ];
    badStateVars = intersect(lower(allTableVars), lower(forbiddenStateVars));
    recordCheck("manifest_represents_no_dynamic_tank_or_header_state", isempty(badStateVars), ...
        "Manifest must not represent dynamic internal tank/header state.");

    allowedLayerResults = ["confirmed", "not_confirmed_homogeneous_surrogate_required"];
    recordCheck("layered_bed_audit_result_allowed", ...
        isfield(manifest.layeredBedAudit, "result") && ...
        ismember(manifest.layeredBedAudit.result, allowedLayerResults), ...
        "Layered-bed audit must either confirm support or label the surrogate.");

    result = packResult();

    function recordCheck(name, didPass, detail)
        didPass = logical(didPass);
        checks = [checks; table(string(name), didPass, string(detail), ...
            'VariableNames', ["check", "passed", "detail"])]; %#ok<AGROW>
        if ~didPass
            failures(end+1, 1) = string(name) + ": " + string(detail); %#ok<AGROW>
        end
    end

    function packed = packResult()
        packed = struct();
        packed.pass = isempty(failures);
        packed.failures = failures;
        packed.warnings = warnings;
        packed.checks = checks;
    end
end
