function result = validateYangDirectTransferPairMap(pairMap, manifest)
%VALIDATEYANGDIRECTTRANSFERPAIRMAP Static WP2 pair-map integrity checks.

    failures = strings(0, 1);
    warnings = strings(0, 1);
    checks = table(strings(0, 1), false(0, 1), strings(0, 1), ...
        'VariableNames', ["check", "passed", "detail"]);

    if nargin < 2 || isempty(manifest)
        manifest = getYangFourBedScheduleManifest();
    end

    if nargin < 1 || isempty(pairMap)
        pairMap = getYangDirectTransferPairMap(manifest);
    end

    if ~isstruct(manifest) || ~isfield(manifest, "bedSteps")
        recordCheck("manifest_has_bed_steps", false, ...
            "Manifest must be a struct with a bedSteps table.");
        result = packResult();
        return;
    end

    if ~isstruct(pairMap)
        recordCheck("pair_map_is_struct", false, ...
            "Pair map input must be a struct.");
        result = packResult();
        return;
    end

    requiredFields = [
        "version"
        "manifestVersion"
        "sourceName"
        "sourceDocument"
        "bedLabels"
        "pairingPolicy"
        "holdupPolicy"
        "eventPolicy"
        "sourceNotes"
        "architecture"
        "endpointMetadata"
        "transferPairs"
    ];

    pairMapFields = string(fieldnames(pairMap));
    for i = 1:numel(requiredFields)
        fieldName = requiredFields(i);
        recordCheck("has_field_" + fieldName, any(pairMapFields == fieldName), ...
            "Required pair-map top-level field.");
    end

    if ~all(ismember(requiredFields, pairMapFields))
        result = packResult();
        return;
    end

    bedSteps = manifest.bedSteps;
    pairs = pairMap.transferPairs;
    endpointMetadata = pairMap.endpointMetadata;

    recordCheck("transfer_pairs_is_table", istable(pairs), ...
        "pairMap.transferPairs must be a table.");
    recordCheck("endpoint_metadata_is_table", istable(endpointMetadata), ...
        "pairMap.endpointMetadata must be a table.");
    if ~istable(pairs) || ~istable(endpointMetadata)
        result = packResult();
        return;
    end

    requiredPairVars = [
        "pair_id"
        "direct_transfer_family"
        "donor_bed"
        "receiver_bed"
        "donor_record_id"
        "receiver_record_id"
        "donor_source_col"
        "receiver_source_col"
        "donor_yang_label"
        "receiver_yang_label"
        "donor_role_class"
        "receiver_role_class"
        "donor_p_start_class"
        "donor_p_end_class"
        "receiver_p_start_class"
        "receiver_p_end_class"
        "donor_internal_transfer_category"
        "receiver_internal_transfer_category"
        "donor_outlet_endpoint"
        "receiver_inlet_endpoint"
        "receiver_waste_endpoint"
        "transfer_accounting_category"
        "source_basis_note"
    ];

    pairVars = string(pairs.Properties.VariableNames);
    missingPairVars = setdiff(requiredPairVars, pairVars);
    recordCheck("transfer_pairs_required_columns", isempty(missingPairVars), ...
        "transferPairs must expose the WP2 pair-map schema.");
    if ~isempty(missingPairVars)
        result = packResult();
        return;
    end

    expectedKeys = expectedPairKeys();
    actualKeys = pairs.direct_transfer_family + ":" + pairs.donor_bed + "->" + pairs.receiver_bed;
    recordCheck("version_nonempty", strlength(string(pairMap.version)) > 0, ...
        "Pair-map version must be nonempty.");
    recordCheck("manifest_version_matches", string(pairMap.manifestVersion) == string(manifest.version), ...
        "Pair map must state the WP1 manifest version it consumes.");
    recordCheck("bed_labels_are_A_B_C_D", isequal(string(pairMap.bedLabels), ["A", "B", "C", "D"]), ...
        "Pair map must cover named beds A, B, C, and D.");
    recordCheck("pairing_policy_is_explicit", ...
        contains(lower(string(pairMap.pairingPolicy)), "explicit") && ...
        contains(lower(string(pairMap.pairingPolicy)), "no_row_order"), ...
        "Pairing policy must forbid row-order inference.");
    recordCheck("transfer_pair_count", height(pairs) == 16, ...
        "WP2 pair map must define sixteen direct-transfer pairs.");
    recordCheck("cyclic_pair_keys_match", isequal(sort(actualKeys), sort(expectedKeys)), ...
        "Pair keys must match the confirmed cyclic map.");

    expectedFamilies = ["ADPP_BF", "EQI", "EQII", "PP_PU"];
    for family = expectedFamilies
        recordCheck("family_" + family + "_has_four_pairs", ...
            sum(pairs.direct_transfer_family == family) == 4, ...
            "Each direct-transfer family must have four explicit bed pairs.");
    end

    recordCheck("donor_receiver_beds_are_distinct", all(pairs.donor_bed ~= pairs.receiver_bed), ...
        "A direct-transfer pair cannot connect a bed to itself.");
    recordCheck("all_beds_are_known", ...
        all(ismember(pairs.donor_bed, pairMap.bedLabels)) && ...
        all(ismember(pairs.receiver_bed, pairMap.bedLabels)), ...
        "Every donor and receiver bed must be one of A, B, C, or D.");
    recordCheck("contains_crossed_nonadjacent_pairs", ...
        any(pairs.direct_transfer_family == "EQI" & pairs.donor_bed == "A" & pairs.receiver_bed == "C") && ...
        any(pairs.direct_transfer_family == "EQI" & pairs.donor_bed == "B" & pairs.receiver_bed == "D"), ...
        "The map must preserve crossed EQI pairs instead of adjacency inference.");
    recordCheck("contains_displayed_source_column_offsets", ...
        any(pairs.donor_source_col ~= pairs.receiver_source_col), ...
        "The map must be explicit rather than same-column-only inference.");

    requiredRows = bedSteps(bedSteps.requires_pair_map, :);
    coveredRecordIds = [pairs.donor_record_id; pairs.receiver_record_id];
    recordCheck("required_pair_rows_covered", ...
        all(ismember(requiredRows.record_id, coveredRecordIds)), ...
        "Every manifest row that requires a pair map must be covered.");
    recordCheck("covered_rows_are_required", ...
        all(ismember(coveredRecordIds, requiredRows.record_id)), ...
        "The pair map must not cover non-direct-transfer rows.");
    recordCheck("required_rows_covered_once", ...
        numel(coveredRecordIds) == height(requiredRows) && ...
        numel(unique(coveredRecordIds)) == numel(coveredRecordIds), ...
        "Every direct-transfer manifest row must appear exactly once as donor or receiver.");

    for row = 1:height(pairs)
        validatePairRow(row);
    end

    arch = pairMap.architecture;
    recordCheck("architecture_no_dynamic_tanks", ...
        isfield(arch, "noDynamicInternalTanks") && arch.noDynamicInternalTanks, ...
        "WP2 must not create dynamic internal tanks.");
    recordCheck("architecture_no_shared_header", ...
        isfield(arch, "noSharedHeaderInventory") && arch.noSharedHeaderInventory, ...
        "WP2 must not create shared header inventory.");
    recordCheck("architecture_no_four_bed_rhs", ...
        isfield(arch, "noFourBedRhsDae") && arch.noFourBedRhsDae, ...
        "WP2 must not assemble a global four-bed RHS/DAE.");
    recordCheck("architecture_no_core_physics_rewrite", ...
        isfield(arch, "noCoreAdsorberPhysicsRewrite") && arch.noCoreAdsorberPhysicsRewrite, ...
        "WP2 must preserve toPSAil core adsorber physics.");
    recordCheck("architecture_wp2_no_state_or_solver", ...
        isfield(arch, "wp2CreatesPhysicalState") && ~arch.wp2CreatesPhysicalState && ...
        isfield(arch, "wp2InvokesSolver") && ~arch.wp2InvokesSolver, ...
        "WP2 must remain a static metadata layer.");

    allTableVars = [
        string(pairs.Properties.VariableNames), ...
        string(endpointMetadata.Properties.VariableNames)
    ];
    forbiddenStateVars = [
        "tank_state"
        "header_inventory"
        "shared_header_inventory"
        "dynamic_tank_inventory"
        "four_bed_state_vector"
        "state_A"
        "state_B"
        "state_C"
        "state_D"
    ];
    badStateVars = intersect(lower(allTableVars), lower(forbiddenStateVars));
    recordCheck("pair_map_has_no_physical_state_fields", isempty(badStateVars), ...
        "WP2 pair map must not represent physical state or tank/header inventory.");

    result = packResult();

    function validatePairRow(rowIndex)
        pair = pairs(rowIndex, :);
        family = pair.direct_transfer_family(1);
        pairId = pair.pair_id(1);
        donor = bedSteps(bedSteps.record_id == pair.donor_record_id(1), :);
        receiver = bedSteps(bedSteps.record_id == pair.receiver_record_id(1), :);
        expected = expectedFamilyMetadata(family);
        endpoint = endpointMetadata(endpointMetadata.direct_transfer_family == family, :);

        recordCheck("pair_" + pairId + "_donor_record_exists", height(donor) == 1, ...
            "Donor record id must exist in manifest.bedSteps.");
        recordCheck("pair_" + pairId + "_receiver_record_exists", height(receiver) == 1, ...
            "Receiver record id must exist in manifest.bedSteps.");
        if height(donor) ~= 1 || height(receiver) ~= 1
            return;
        end

        recordCheck("pair_" + pairId + "_family_matches_manifest", ...
            donor.direct_transfer_family(1) == family && ...
            receiver.direct_transfer_family(1) == family, ...
            "Donor and receiver manifest rows must share the pair family.");
        recordCheck("pair_" + pairId + "_bed_metadata_matches_manifest", ...
            donor.bed(1) == pair.donor_bed(1) && ...
            receiver.bed(1) == pair.receiver_bed(1), ...
            "Pair bed labels must match manifest rows.");
        recordCheck("pair_" + pairId + "_source_cols_match_manifest", ...
            donor.source_col(1) == pair.donor_source_col(1) && ...
            receiver.source_col(1) == pair.receiver_source_col(1), ...
            "Pair source columns must match manifest rows.");
        recordCheck("pair_" + pairId + "_labels_match_family", ...
            pair.donor_yang_label(1) == expected.donorLabel && ...
            pair.receiver_yang_label(1) == expected.receiverLabel && ...
            donor.yang_label(1) == expected.donorLabel && ...
            receiver.yang_label(1) == expected.receiverLabel, ...
            "Yang labels must match the direct-transfer family.");
        recordCheck("pair_" + pairId + "_roles_match_family", ...
            pair.donor_role_class(1) == expected.donorRole && ...
            pair.receiver_role_class(1) == expected.receiverRole && ...
            donor.role_class(1) == expected.donorRole && ...
            receiver.role_class(1) == expected.receiverRole, ...
            "Donor and receiver roles must match the family direction.");
        recordCheck("pair_" + pairId + "_pressure_classes_match_manifest", ...
            donor.p_start_class(1) == pair.donor_p_start_class(1) && ...
            donor.p_end_class(1) == pair.donor_p_end_class(1) && ...
            receiver.p_start_class(1) == pair.receiver_p_start_class(1) && ...
            receiver.p_end_class(1) == pair.receiver_p_end_class(1), ...
            "Pair pressure classes must copy manifest pressure metadata.");
        recordCheck("pair_" + pairId + "_pressure_classes_match_family", ...
            pair.donor_p_start_class(1) == expected.donorPStart && ...
            pair.donor_p_end_class(1) == expected.donorPEnd && ...
            pair.receiver_p_start_class(1) == expected.receiverPStart && ...
            pair.receiver_p_end_class(1) == expected.receiverPEnd, ...
            "Pair pressure classes must match the family semantics.");
        recordCheck("pair_" + pairId + "_internal_categories_match_family", ...
            pair.donor_internal_transfer_category(1) == expected.donorCategory && ...
            pair.receiver_internal_transfer_category(1) == expected.receiverCategory, ...
            "Internal-transfer categories must preserve donor/receiver direction.");
        recordCheck("pair_" + pairId + "_endpoint_metadata_exists", height(endpoint) == 1, ...
            "Endpoint metadata must have one row for the pair family.");
        if height(endpoint) == 1
            recordCheck("pair_" + pairId + "_endpoints_match_family", ...
                pair.donor_outlet_endpoint(1) == endpoint.donor_outlet_endpoint(1) && ...
                pair.receiver_inlet_endpoint(1) == endpoint.receiver_inlet_endpoint(1) && ...
                pair.receiver_waste_endpoint(1) == endpoint.receiver_waste_endpoint(1) && ...
                pair.transfer_accounting_category(1) == endpoint.transfer_accounting_category(1), ...
                "Pair endpoint and accounting metadata must match family metadata.");
        end
        if family == "ADPP_BF"
            recordCheck("pair_" + pairId + "_adpp_is_compound", donor.is_compound(1), ...
                "AD&PP donor must remain a compound operation.");
        end
        if family == "PP_PU"
            recordCheck("pair_" + pairId + "_pu_waste_exits_feed_end", ...
                pair.receiver_waste_endpoint(1) == "feed_end", ...
                "PU receiver waste endpoint must be feed_end.");
        end
    end

    function recordCheck(name, didPass, detail)
        didPass = logical(didPass);
        checks = [checks; table(string(name), didPass, string(detail), ...
            'VariableNames', ["check", "passed", "detail"])]; %#ok<AGROW>
        if ~didPass
            failures(end+1, 1) = string(name) + ": " + string(detail); %#ok<AGROW>
        end
    end

    function packed = packResult()
        packed = struct();
        packed.pass = isempty(failures);
        packed.failures = failures;
        packed.warnings = warnings;
        packed.checks = checks;
    end
end

function keys = expectedPairKeys()
    keys = [
        "ADPP_BF:A->B"
        "ADPP_BF:B->C"
        "ADPP_BF:C->D"
        "ADPP_BF:D->A"
        "EQI:A->C"
        "EQI:B->D"
        "EQI:C->A"
        "EQI:D->B"
        "EQII:A->D"
        "EQII:B->A"
        "EQII:C->B"
        "EQII:D->C"
        "PP_PU:A->D"
        "PP_PU:B->A"
        "PP_PU:C->B"
        "PP_PU:D->C"
    ];
end

function expected = expectedFamilyMetadata(family)
    switch family
        case "ADPP_BF"
            expected = struct( ...
                "donorLabel", "AD&PP", ...
                "receiverLabel", "BF", ...
                "donorRole", "compound_donor", ...
                "receiverRole", "receiver", ...
                "donorPStart", "PF", ...
                "donorPEnd", "PF", ...
                "receiverPStart", "P6", ...
                "receiverPEnd", "PF", ...
                "donorCategory", "backfill_donor", ...
                "receiverCategory", "backfill_receiver" ...
            );
        case "EQI"
            expected = struct( ...
                "donorLabel", "EQI-BD", ...
                "receiverLabel", "EQI-PR", ...
                "donorRole", "donor", ...
                "receiverRole", "receiver", ...
                "donorPStart", "PF", ...
                "donorPEnd", "P1", ...
                "receiverPStart", "P5", ...
                "receiverPEnd", "P6", ...
                "donorCategory", "equalization_donor", ...
                "receiverCategory", "equalization_receiver" ...
            );
        case "EQII"
            expected = struct( ...
                "donorLabel", "EQII-BD", ...
                "receiverLabel", "EQII-PR", ...
                "donorRole", "donor", ...
                "receiverRole", "receiver", ...
                "donorPStart", "P2", ...
                "donorPEnd", "P3", ...
                "receiverPStart", "P4", ...
                "receiverPEnd", "P5", ...
                "donorCategory", "equalization_donor", ...
                "receiverCategory", "equalization_receiver" ...
            );
        case "PP_PU"
            expected = struct( ...
                "donorLabel", "PP", ...
                "receiverLabel", "PU", ...
                "donorRole", "donor", ...
                "receiverRole", "receiver_with_external_waste", ...
                "donorPStart", "P1", ...
                "donorPEnd", "P2", ...
                "receiverPStart", "P4", ...
                "receiverPEnd", "P4", ...
                "donorCategory", "provide_purge_donor", ...
                "receiverCategory", "provide_purge_receiver" ...
            );
        otherwise
            error('WP2:UnknownDirectTransferFamily', ...
                'Unknown direct-transfer family %s.', char(family));
    end
end
